#pragma once

#define CRUDE_CORE_LOG_MESSAGE_BUFFER_MAX_LENGTH CRUDE_RKILO( 8 )
#define CRUDE_CORE_LOG_FORMAT_BUFFER_MAX_LENGTH  CRUDE_RKILO( 8 )
#define CRUDE_CORE_HASHMAP_INITIAL_CAPACITY 16
#define CRUDE_CORE_PROCESS_LOGGER_BUFFER_SIZE 256
#define CRUDE_CORE_PROCESS_OUTPUT_BUFFER_SIZE 1024