/* okay I give up... directxmath is too good not to use */
#include <DirectXMath.h>
#include <math.h>

#include <core/alias.h>
#include <core/components_serialization.h>

using namespace DirectX;

#define CRUDE_FLOOR( a ) floor( a )
#define CRUDE_CEIL( a ) ceil( a )
#define CRUDE_MAX( a, b ) fmaxf( a, b )
#define CRUDE_MIN( a, b ) fminf( a, b )
#define CRUDE_CLAMP( x, u, l ) CRUDE_MIN( u, CRUDE_MAX( x, l ) )

CRUDE_API float32
crude_random_unit_f32
(
);

CRUDE_API CRUDE_PARSE_JSON_TO_COMPONENT_FUNC_DECLARATION( XMFLOAT2 );
CRUDE_API CRUDE_PARSE_JSON_TO_COMPONENT_FUNC_DECLARATION( XMFLOAT3 );
CRUDE_API CRUDE_PARSE_JSON_TO_COMPONENT_FUNC_DECLARATION( XMFLOAT4 );

CRUDE_API CRUDE_PARSE_COMPONENT_TO_JSON_FUNC_DECLARATION( XMFLOAT2 );
CRUDE_API CRUDE_PARSE_COMPONENT_TO_JSON_FUNC_DECLARATION( XMFLOAT3 );
CRUDE_API CRUDE_PARSE_COMPONENT_TO_JSON_FUNC_DECLARATION( XMFLOAT4 );

CRUDE_API CRUDE_COMPONENT_STRING_DECLARE( XMFLOAT2, "float2" );
CRUDE_API CRUDE_COMPONENT_STRING_DECLARE( XMFLOAT3, "float3" );
CRUDE_API CRUDE_COMPONENT_STRING_DECLARE( XMFLOAT4, "float4" );