#pragma once

#define CRUDE_GFX_TEXTURE_NAME_MAX                         ( 512 )

#define CRUDE_GFX_MESHLET_MAX_VERTICES                     ( 128 )
#define CRUDE_GFX_MESHLET_MAX_TRIANGLES                    ( 124 )
#define CRUDE_GFX_MESHLET_CONE_WEIGHT                      ( 0.0 )

#define CRUDE_GFX_ASYNCHRONOUS_LOADER_UPLOAD_REQUESTS_LIMIT ( 1024 )
#define CRUDE_GFX_ASYNCHRONOUS_LOADER_FILE_LOAD_REQUESTS_LIMIT ( 1024 )

#define CRUDE_GFX_SWAPCHAIN_BARRIER_COMMAND_BUFFER_THREAD_ID ( 0 )
#define CRUDE_GFX_TEXTURE_COPY_FROM_BUFFER_THREAD_ID       ( 0 )
#define CRUDE_GFX_TEXTURE_UPDATE_COMMANDS_THREAD_ID        ( 1 )

#define CRUDE_GFX_TECHNIQUE_NAME_MAX_LENGTH                ( 1024 )
#define CRUDE_GFX_TECHNIQUE_RELATIIVE_FILEPATH_MAX_LENGTH  ( 1024 )

#define CRUDE_GFX_FRAMEBUFFER_NAME_MAX_LENGTH              ( 1024 )

#define CRUDE_GFX_FRAME_DESCRIPTOR_POOL_ELEMENTES_COUNT    ( 1024 )
#define CRUDE_GFX_DEPTH_AND_STENCIL_CLEAR_COLOR_INDEX      ( 8 )
#define CRUDE_GFX_SWAPCHAIN_IMAGES_MAX_COUNT               ( 3 )
#define CRUDE_GFX_IMAGE_OUTPUTS_MAX_COUNT                  ( 8 )
#define CRUDE_GFX_DESCRIPTOR_SET_LAYOUTS_MAX_COUNT         ( 8 )
#define CRUDE_GFX_SHADER_STAGES_MAX_COUNT                  ( 5 )
#define CRUDE_GFX_DESCRIPTORS_PER_SET_MAX_COUNT            ( 64 )
#define CRUDE_GFX_UBO_ALIGNMENT                            ( 256 )
#define CRUDE_GFX_SET_MAX_COUNT                            ( 32 )
#define CRUDE_GFX_BINDLESS_RESOURCES_MAX_COUNT             ( 1024 )
#define CRUDE_GFX_DEPTH_PYRAMID_PASS_MAX_LEVELS            ( 16 )
#define CRUDE_GFX_TETRAHEDRON_SHADOWMAP_SIZE               ( 8192 )

#define CRUDE_GFX_RENDER_GRAPH_RESOURCES_MAX_COUNT         ( 1024 )
#define CRUDE_GFX_RENDER_GRAPH_NODES_MAX_COUNT             ( 1024 )

#define CRUDE_GFX_SCENE_RENDERER_MAX_DEBUG_LINES           ( 640000 )
#define CRUDE_GFX_SCENE_RENDERER_MAX_DEBUG_CUBES           ( 60000 )
#define CRUDE_GFX_SCENE_RENDERER_MESH_INSTANCES_BUFFER_CAPACITY ( 200 )
#define CRUDE_GFX_SCENE_RENDERER_COLLISION_MESH_INSTANCES_BUFFER_CAPACITY ( 200 )

#define CRUDE_GFX_DEVICE_HEAP_ALLOCATOR_MIN_BLOCK_SIZE     ( 16 )
#define CRUDE_GFX_DEVICE_HEAP_ALLOCATOR_DEFAULT_ALIGN      ( 16 )
#define CRUDE_GFX_DEVICE_HEAP_ALLOCATOR_DEFAULT_ALLOCATION_STRATEGY ( 1 )

#define CRUDE_GFX_PRESENT_TEXTURE_NAME "editor_final"