#pragma once

#include <engine/core/alias.h>
#include <engine/graphics/graphics_config.h>

#define CRUDE_GFX_RHI_TO_IMPLEMENTIT ___DOIT

#if CRUDE_GFX_VULKAN
#include <vulkan/vulkan.h>
#include <vulkan/vk_enum_string_helper.h>
#include <vulkan/vulkan.h>
#include <thirdparty/vma/include/vk_mem_alloc.h>
#include <SDL3/SDL_vulkan.h>
#include <thirdparty/imgui/backends/imgui_impl_vulkan.h>
#elif CRUDE_GFX_NAPI
#else
CRUDE_GFX_RHI_TO_IMPLEMENTIT
#endif

typedef enum crude_gfx_rhi_resource_state
{
  CRUDE_GFX_RHI_RESOURCE_STATE_UNDEFINED = 0,
  CRUDE_GFX_RHI_RESOURCE_STATE_VERTEX_AND_CONSTANT_BUFFER = 0x1,
  CRUDE_GFX_RHI_RESOURCE_STATE_INDEX_BUFFER = 0x2,
  CRUDE_GFX_RHI_RESOURCE_STATE_RENDER_TARGET = 0x4,
  CRUDE_GFX_RHI_RESOURCE_STATE_UNORDERED_ACCESS = 0x8,
  CRUDE_GFX_RHI_RESOURCE_STATE_DEPTH_WRITE = 0x10,
  CRUDE_GFX_RHI_RESOURCE_STATE_DEPTH_READ = 0x20,
  CRUDE_GFX_RHI_RESOURCE_STATE_NON_PIXEL_SHADER_RESOURCE = 0x40,
  CRUDE_GFX_RHI_RESOURCE_STATE_PIXEL_SHADER_RESOURCE = 0x80,
  CRUDE_GFX_RHI_RESOURCE_STATE_SHADER_RESOURCE = 0x40 | 0x80,
  CRUDE_GFX_RHI_RESOURCE_STATE_STREAM_OUT = 0x100,
  CRUDE_GFX_RHI_RESOURCE_STATE_INDIRECT_ARGUMENT = 0x200,
  CRUDE_GFX_RHI_RESOURCE_STATE_COPY_DEST = 0x400,
  CRUDE_GFX_RHI_RESOURCE_STATE_COPY_SOURCE = 0x800,
  CRUDE_GFX_RHI_RESOURCE_STATE_GENERIC_READ = ( ( ( ( ( 0x1 | 0x2 ) | 0x40 ) | 0x80 ) | 0x200 ) | 0x800 ),
  CRUDE_GFX_RHI_RESOURCE_STATE_PRESENT = 0x1000,
  CRUDE_GFX_RHI_RESOURCE_STATE_COMMON = 0x2000,
  CRUDE_GFX_RHI_RESOURCE_STATE_RAYTRACING_ACCELERATION_STRUCTURE = 0x4000,
  CRUDE_GFX_RHI_RESOURCE_STATE_SHADING_RATE_SOURCE = 0x8000,
} crude_gfx_rhi_resource_state;

char const*
crude_gfx_rhi_resource_state_to_name
(
  _In_ crude_gfx_rhi_resource_state                        value
);

#if CRUDE_GFX_VULKAN
typedef enum crude_gfx_rhi_format
{
  CRUDE_GFX_RHI_FORMAT_UNDEFINED = VK_FORMAT_UNDEFINED,
  CRUDE_GFX_RHI_FORMAT_R4G4_UNORM_PACK8 = VK_FORMAT_R4G4_UNORM_PACK8,
  CRUDE_GFX_RHI_FORMAT_R4G4B4A4_UNORM_PACK16 = VK_FORMAT_R4G4B4A4_UNORM_PACK16,
  CRUDE_GFX_RHI_FORMAT_B4G4R4A4_UNORM_PACK16 = VK_FORMAT_B4G4R4A4_UNORM_PACK16,
  CRUDE_GFX_RHI_FORMAT_R5G6B5_UNORM_PACK16 = VK_FORMAT_R5G6B5_UNORM_PACK16,
  CRUDE_GFX_RHI_FORMAT_B5G6R5_UNORM_PACK16 = VK_FORMAT_B5G6R5_UNORM_PACK16,
  CRUDE_GFX_RHI_FORMAT_R5G5B5A1_UNORM_PACK16 = VK_FORMAT_R5G5B5A1_UNORM_PACK16,
  CRUDE_GFX_RHI_FORMAT_B5G5R5A1_UNORM_PACK16 = VK_FORMAT_B5G5R5A1_UNORM_PACK16,
  CRUDE_GFX_RHI_FORMAT_A1R5G5B5_UNORM_PACK16 = VK_FORMAT_A1R5G5B5_UNORM_PACK16,
  CRUDE_GFX_RHI_FORMAT_R8_UNORM = VK_FORMAT_R8_UNORM,
  CRUDE_GFX_RHI_FORMAT_R8_SNORM = VK_FORMAT_R8_SNORM,
  CRUDE_GFX_RHI_FORMAT_R8_USCALED = VK_FORMAT_R8_USCALED,
  CRUDE_GFX_RHI_FORMAT_R8_SSCALED = VK_FORMAT_R8_SSCALED,
  CRUDE_GFX_RHI_FORMAT_R8_UINT = VK_FORMAT_R8_UINT,
  CRUDE_GFX_RHI_FORMAT_R8_SINT = VK_FORMAT_R8_SINT,
  CRUDE_GFX_RHI_FORMAT_R8_SRGB = VK_FORMAT_R8_SRGB,
  CRUDE_GFX_RHI_FORMAT_R8G8_UNORM = VK_FORMAT_R8G8_UNORM,
  CRUDE_GFX_RHI_FORMAT_R8G8_SNORM = VK_FORMAT_R8G8_SNORM,
  CRUDE_GFX_RHI_FORMAT_R8G8_USCALED = VK_FORMAT_R8G8_USCALED,
  CRUDE_GFX_RHI_FORMAT_R8G8_SSCALED = VK_FORMAT_R8G8_SSCALED,
  CRUDE_GFX_RHI_FORMAT_R8G8_UINT = VK_FORMAT_R8G8_UINT,
  CRUDE_GFX_RHI_FORMAT_R8G8_SINT = VK_FORMAT_R8G8_SINT,
  CRUDE_GFX_RHI_FORMAT_R8G8_SRGB = VK_FORMAT_R8G8_SRGB,
  CRUDE_GFX_RHI_FORMAT_R8G8B8_UNORM = VK_FORMAT_R8G8B8_UNORM,
  CRUDE_GFX_RHI_FORMAT_R8G8B8_SNORM = VK_FORMAT_R8G8B8_SNORM,
  CRUDE_GFX_RHI_FORMAT_R8G8B8_USCALED = VK_FORMAT_R8G8B8_USCALED,
  CRUDE_GFX_RHI_FORMAT_R8G8B8_SSCALED = VK_FORMAT_R8G8B8_SSCALED,
  CRUDE_GFX_RHI_FORMAT_R8G8B8_UINT = VK_FORMAT_R8G8B8_UINT,
  CRUDE_GFX_RHI_FORMAT_R8G8B8_SINT = VK_FORMAT_R8G8B8_SINT,
  CRUDE_GFX_RHI_FORMAT_R8G8B8_SRGB = VK_FORMAT_R8G8B8_SRGB,
  CRUDE_GFX_RHI_FORMAT_B8G8R8_UNORM = VK_FORMAT_B8G8R8_UNORM,
  CRUDE_GFX_RHI_FORMAT_B8G8R8_SNORM = VK_FORMAT_B8G8R8_SNORM,
  CRUDE_GFX_RHI_FORMAT_B8G8R8_USCALED = VK_FORMAT_B8G8R8_USCALED,
  CRUDE_GFX_RHI_FORMAT_B8G8R8_SSCALED = VK_FORMAT_B8G8R8_SSCALED,
  CRUDE_GFX_RHI_FORMAT_B8G8R8_UINT = VK_FORMAT_B8G8R8_UINT,
  CRUDE_GFX_RHI_FORMAT_B8G8R8_SINT = VK_FORMAT_B8G8R8_SINT,
  CRUDE_GFX_RHI_FORMAT_B8G8R8_SRGB = VK_FORMAT_B8G8R8_SRGB,
  CRUDE_GFX_RHI_FORMAT_R8G8B8A8_UNORM = VK_FORMAT_R8G8B8A8_UNORM,
  CRUDE_GFX_RHI_FORMAT_R8G8B8A8_SNORM = VK_FORMAT_R8G8B8A8_SNORM,
  CRUDE_GFX_RHI_FORMAT_R8G8B8A8_USCALED = VK_FORMAT_R8G8B8A8_USCALED,
  CRUDE_GFX_RHI_FORMAT_R8G8B8A8_SSCALED = VK_FORMAT_R8G8B8A8_SSCALED,
  CRUDE_GFX_RHI_FORMAT_R8G8B8A8_UINT = VK_FORMAT_R8G8B8A8_UINT,
  CRUDE_GFX_RHI_FORMAT_R8G8B8A8_SINT = VK_FORMAT_R8G8B8A8_SINT,
  CRUDE_GFX_RHI_FORMAT_R8G8B8A8_SRGB = VK_FORMAT_R8G8B8A8_SRGB,
  CRUDE_GFX_RHI_FORMAT_B8G8R8A8_UNORM = VK_FORMAT_B8G8R8A8_UNORM,
  CRUDE_GFX_RHI_FORMAT_B8G8R8A8_SNORM = VK_FORMAT_B8G8R8A8_SNORM,
  CRUDE_GFX_RHI_FORMAT_B8G8R8A8_USCALED = VK_FORMAT_B8G8R8A8_USCALED,
  CRUDE_GFX_RHI_FORMAT_B8G8R8A8_SSCALED = VK_FORMAT_B8G8R8A8_SSCALED,
  CRUDE_GFX_RHI_FORMAT_B8G8R8A8_UINT = VK_FORMAT_B8G8R8A8_UINT,
  CRUDE_GFX_RHI_FORMAT_B8G8R8A8_SINT = VK_FORMAT_B8G8R8A8_SINT,
  CRUDE_GFX_RHI_FORMAT_B8G8R8A8_SRGB = VK_FORMAT_B8G8R8A8_SRGB,
  CRUDE_GFX_RHI_FORMAT_A8B8G8R8_UNORM_PACK32 = VK_FORMAT_A8B8G8R8_UNORM_PACK32,
  CRUDE_GFX_RHI_FORMAT_A8B8G8R8_SNORM_PACK32 = VK_FORMAT_A8B8G8R8_SNORM_PACK32,
  CRUDE_GFX_RHI_FORMAT_A8B8G8R8_USCALED_PACK32 = VK_FORMAT_A8B8G8R8_USCALED_PACK32,
  CRUDE_GFX_RHI_FORMAT_A8B8G8R8_SSCALED_PACK32 = VK_FORMAT_A8B8G8R8_SSCALED_PACK32,
  CRUDE_GFX_RHI_FORMAT_A8B8G8R8_UINT_PACK32 = VK_FORMAT_A8B8G8R8_UINT_PACK32,
  CRUDE_GFX_RHI_FORMAT_A8B8G8R8_SINT_PACK32 = VK_FORMAT_A8B8G8R8_SINT_PACK32,
  CRUDE_GFX_RHI_FORMAT_A8B8G8R8_SRGB_PACK32 = VK_FORMAT_A8B8G8R8_SRGB_PACK32,
  CRUDE_GFX_RHI_FORMAT_A2R10G10B10_UNORM_PACK32 = VK_FORMAT_A2R10G10B10_UNORM_PACK32,
  CRUDE_GFX_RHI_FORMAT_A2R10G10B10_SNORM_PACK32 = VK_FORMAT_A2R10G10B10_SNORM_PACK32,
  CRUDE_GFX_RHI_FORMAT_A2R10G10B10_USCALED_PACK32 = VK_FORMAT_A2R10G10B10_USCALED_PACK32,
  CRUDE_GFX_RHI_FORMAT_A2R10G10B10_SSCALED_PACK32 = VK_FORMAT_A2R10G10B10_SSCALED_PACK32,
  CRUDE_GFX_RHI_FORMAT_A2R10G10B10_UINT_PACK32 = VK_FORMAT_A2R10G10B10_UINT_PACK32,
  CRUDE_GFX_RHI_FORMAT_A2R10G10B10_SINT_PACK32 = VK_FORMAT_A2R10G10B10_SINT_PACK32,
  CRUDE_GFX_RHI_FORMAT_A2B10G10R10_UNORM_PACK32 = VK_FORMAT_A2B10G10R10_UNORM_PACK32,
  CRUDE_GFX_RHI_FORMAT_A2B10G10R10_SNORM_PACK32 = VK_FORMAT_A2B10G10R10_SNORM_PACK32,
  CRUDE_GFX_RHI_FORMAT_A2B10G10R10_USCALED_PACK32 = VK_FORMAT_A2B10G10R10_USCALED_PACK32,
  CRUDE_GFX_RHI_FORMAT_A2B10G10R10_SSCALED_PACK32 = VK_FORMAT_A2B10G10R10_SSCALED_PACK32,
  CRUDE_GFX_RHI_FORMAT_A2B10G10R10_UINT_PACK32 = VK_FORMAT_A2B10G10R10_UINT_PACK32,
  CRUDE_GFX_RHI_FORMAT_A2B10G10R10_SINT_PACK32 = VK_FORMAT_A2B10G10R10_SINT_PACK32,
  CRUDE_GFX_RHI_FORMAT_R16_UNORM = VK_FORMAT_R16_UNORM,
  CRUDE_GFX_RHI_FORMAT_R16_SNORM = VK_FORMAT_R16_SNORM,
  CRUDE_GFX_RHI_FORMAT_R16_USCALED = VK_FORMAT_R16_USCALED,
  CRUDE_GFX_RHI_FORMAT_R16_SSCALED = VK_FORMAT_R16_SSCALED,
  CRUDE_GFX_RHI_FORMAT_R16_UINT = VK_FORMAT_R16_UINT,
  CRUDE_GFX_RHI_FORMAT_R16_SINT = VK_FORMAT_R16_SINT,
  CRUDE_GFX_RHI_FORMAT_R16_SFLOAT = VK_FORMAT_R16_SFLOAT,
  CRUDE_GFX_RHI_FORMAT_R16G16_UNORM = VK_FORMAT_R16G16_UNORM,
  CRUDE_GFX_RHI_FORMAT_R16G16_SNORM = VK_FORMAT_R16G16_SNORM,
  CRUDE_GFX_RHI_FORMAT_R16G16_USCALED = VK_FORMAT_R16G16_USCALED,
  CRUDE_GFX_RHI_FORMAT_R16G16_SSCALED = VK_FORMAT_R16G16_SSCALED,
  CRUDE_GFX_RHI_FORMAT_R16G16_UINT = VK_FORMAT_R16G16_UINT,
  CRUDE_GFX_RHI_FORMAT_R16G16_SINT = VK_FORMAT_R16G16_SINT,
  CRUDE_GFX_RHI_FORMAT_R16G16_SFLOAT = VK_FORMAT_R16G16_SFLOAT,
  CRUDE_GFX_RHI_FORMAT_R16G16B16_UNORM = VK_FORMAT_R16G16B16_UNORM,
  CRUDE_GFX_RHI_FORMAT_R16G16B16_SNORM = VK_FORMAT_R16G16B16_SNORM,
  CRUDE_GFX_RHI_FORMAT_R16G16B16_USCALED = VK_FORMAT_R16G16B16_USCALED,
  CRUDE_GFX_RHI_FORMAT_R16G16B16_SSCALED = VK_FORMAT_R16G16B16_SSCALED,
  CRUDE_GFX_RHI_FORMAT_R16G16B16_UINT = VK_FORMAT_R16G16B16_UINT,
  CRUDE_GFX_RHI_FORMAT_R16G16B16_SINT = VK_FORMAT_R16G16B16_SINT,
  CRUDE_GFX_RHI_FORMAT_R16G16B16_SFLOAT = VK_FORMAT_R16G16B16_SFLOAT,
  CRUDE_GFX_RHI_FORMAT_R16G16B16A16_UNORM = VK_FORMAT_R16G16B16A16_UNORM,
  CRUDE_GFX_RHI_FORMAT_R16G16B16A16_SNORM = VK_FORMAT_R16G16B16A16_SNORM,
  CRUDE_GFX_RHI_FORMAT_R16G16B16A16_USCALED = VK_FORMAT_R16G16B16A16_USCALED,
  CRUDE_GFX_RHI_FORMAT_R16G16B16A16_SSCALED = VK_FORMAT_R16G16B16A16_SSCALED,
  CRUDE_GFX_RHI_FORMAT_R16G16B16A16_UINT = VK_FORMAT_R16G16B16A16_UINT,
  CRUDE_GFX_RHI_FORMAT_R16G16B16A16_SINT = VK_FORMAT_R16G16B16A16_SINT,
  CRUDE_GFX_RHI_FORMAT_R16G16B16A16_SFLOAT = VK_FORMAT_R16G16B16A16_SFLOAT,
  CRUDE_GFX_RHI_FORMAT_R32_UINT = VK_FORMAT_R32_UINT,
  CRUDE_GFX_RHI_FORMAT_R32_SINT = VK_FORMAT_R32_SINT,
  CRUDE_GFX_RHI_FORMAT_R32_SFLOAT = VK_FORMAT_R32_SFLOAT,
  CRUDE_GFX_RHI_FORMAT_R32G32_UINT = VK_FORMAT_R32G32_UINT,
  CRUDE_GFX_RHI_FORMAT_R32G32_SINT = VK_FORMAT_R32G32_SINT,
  CRUDE_GFX_RHI_FORMAT_R32G32_SFLOAT = VK_FORMAT_R32G32_SFLOAT,
  CRUDE_GFX_RHI_FORMAT_R32G32B32_UINT = VK_FORMAT_R32G32B32_UINT,
  CRUDE_GFX_RHI_FORMAT_R32G32B32_SINT = VK_FORMAT_R32G32B32_SINT,
  CRUDE_GFX_RHI_FORMAT_R32G32B32_SFLOAT = VK_FORMAT_R32G32B32_SFLOAT,
  CRUDE_GFX_RHI_FORMAT_R32G32B32A32_UINT = VK_FORMAT_R32G32B32A32_UINT,
  CRUDE_GFX_RHI_FORMAT_R32G32B32A32_SINT = VK_FORMAT_R32G32B32A32_SINT,
  CRUDE_GFX_RHI_FORMAT_R32G32B32A32_SFLOAT = VK_FORMAT_R32G32B32A32_SFLOAT,
  CRUDE_GFX_RHI_FORMAT_R64_UINT = VK_FORMAT_R64_UINT,
  CRUDE_GFX_RHI_FORMAT_R64_SINT = VK_FORMAT_R64_SINT,
  CRUDE_GFX_RHI_FORMAT_R64_SFLOAT = VK_FORMAT_R64_SFLOAT,
  CRUDE_GFX_RHI_FORMAT_R64G64_UINT = VK_FORMAT_R64G64_UINT,
  CRUDE_GFX_RHI_FORMAT_R64G64_SINT = VK_FORMAT_R64G64_SINT,
  CRUDE_GFX_RHI_FORMAT_R64G64_SFLOAT = VK_FORMAT_R64G64_SFLOAT,
  CRUDE_GFX_RHI_FORMAT_R64G64B64_UINT = VK_FORMAT_R64G64B64_UINT,
  CRUDE_GFX_RHI_FORMAT_R64G64B64_SINT = VK_FORMAT_R64G64B64_SINT,
  CRUDE_GFX_RHI_FORMAT_R64G64B64_SFLOAT = VK_FORMAT_R64G64B64_SFLOAT,
  CRUDE_GFX_RHI_FORMAT_R64G64B64A64_UINT = VK_FORMAT_R64G64B64A64_UINT,
  CRUDE_GFX_RHI_FORMAT_R64G64B64A64_SINT = VK_FORMAT_R64G64B64A64_SINT,
  CRUDE_GFX_RHI_FORMAT_R64G64B64A64_SFLOAT = VK_FORMAT_R64G64B64A64_SFLOAT,
  CRUDE_GFX_RHI_FORMAT_B10G11R11_UFLOAT_PACK32 = VK_FORMAT_B10G11R11_UFLOAT_PACK32,
  CRUDE_GFX_RHI_FORMAT_E5B9G9R9_UFLOAT_PACK32 = VK_FORMAT_E5B9G9R9_UFLOAT_PACK32,
  CRUDE_GFX_RHI_FORMAT_D16_UNORM = VK_FORMAT_D16_UNORM,
  CRUDE_GFX_RHI_FORMAT_X8_D24_UNORM_PACK32 = VK_FORMAT_X8_D24_UNORM_PACK32,
  CRUDE_GFX_RHI_FORMAT_D32_SFLOAT = VK_FORMAT_D32_SFLOAT,
  CRUDE_GFX_RHI_FORMAT_S8_UINT = VK_FORMAT_S8_UINT,
  CRUDE_GFX_RHI_FORMAT_D16_UNORM_S8_UINT = VK_FORMAT_D16_UNORM_S8_UINT,
  CRUDE_GFX_RHI_FORMAT_D24_UNORM_S8_UINT = VK_FORMAT_D24_UNORM_S8_UINT,
  CRUDE_GFX_RHI_FORMAT_D32_SFLOAT_S8_UINT = VK_FORMAT_D32_SFLOAT_S8_UINT,
} crude_gfx_rhi_format;

typedef enum crude_gfx_rhi_stencil_op
{
} crude_gfx_rhi_stencil_op;

typedef enum crude_gfx_rhi_compare_op
{
  CRUDE_GFX_RHI_COMPARE_OP_NEVER = VK_COMPARE_OP_NEVER,
  CRUDE_GFX_RHI_COMPARE_OP_LESS = VK_COMPARE_OP_LESS,
  CRUDE_GFX_RHI_COMPARE_OP_EQUAL = VK_COMPARE_OP_EQUAL,
  CRUDE_GFX_RHI_COMPARE_OP_LESS_OR_EQUAL = VK_COMPARE_OP_LESS_OR_EQUAL,
  CRUDE_GFX_RHI_COMPARE_OP_GREATER = VK_COMPARE_OP_GREATER,
  CRUDE_GFX_RHI_COMPARE_OP_NOT_EQUAL = VK_COMPARE_OP_NOT_EQUAL,
  CRUDE_GFX_RHI_COMPARE_OP_GREATER_OR_EQUAL = VK_COMPARE_OP_GREATER_OR_EQUAL,
  CRUDE_GFX_RHI_COMPARE_OP_ALWAYS = VK_COMPARE_OP_ALWAYS,
  CRUDE_GFX_RHI_COMPARE_OP_MAX_ENUM = VK_COMPARE_OP_MAX_ENUM
} crude_gfx_rhi_compare_op;

typedef enum crude_gfx_rhi_blend_factor
{
  CRUDE_GFX_RHI_BLEND_FACTOR_ZERO = VK_BLEND_FACTOR_ZERO,
  CRUDE_GFX_RHI_BLEND_FACTOR_ONE = VK_BLEND_FACTOR_ONE,
  CRUDE_GFX_RHI_BLEND_FACTOR_SRC_COLOR = VK_BLEND_FACTOR_SRC_COLOR,
  CRUDE_GFX_RHI_BLEND_FACTOR_ONE_MINUS_SRC_COLOR = VK_BLEND_FACTOR_ONE_MINUS_SRC_COLOR,
  CRUDE_GFX_RHI_BLEND_FACTOR_DST_COLOR = VK_BLEND_FACTOR_DST_COLOR,
  CRUDE_GFX_RHI_BLEND_FACTOR_ONE_MINUS_DST_COLOR = VK_BLEND_FACTOR_ONE_MINUS_DST_COLOR,
  CRUDE_GFX_RHI_BLEND_FACTOR_SRC_ALPHA = VK_BLEND_FACTOR_SRC_ALPHA,
  CRUDE_GFX_RHI_BLEND_FACTOR_ONE_MINUS_SRC_ALPHA = VK_BLEND_FACTOR_ONE_MINUS_SRC_ALPHA,
  CRUDE_GFX_RHI_BLEND_FACTOR_DST_ALPHA = VK_BLEND_FACTOR_DST_ALPHA,
  CRUDE_GFX_RHI_BLEND_FACTOR_ONE_MINUS_DST_ALPHA = VK_BLEND_FACTOR_ONE_MINUS_DST_ALPHA,
  CRUDE_GFX_RHI_BLEND_FACTOR_CONSTANT_COLOR = VK_BLEND_FACTOR_CONSTANT_COLOR,
  CRUDE_GFX_RHI_BLEND_FACTOR_ONE_MINUS_CONSTANT_COLOR = VK_BLEND_FACTOR_ONE_MINUS_CONSTANT_COLOR,
  CRUDE_GFX_RHI_BLEND_FACTOR_CONSTANT_ALPHA = VK_BLEND_FACTOR_CONSTANT_ALPHA,
  CRUDE_GFX_RHI_BLEND_FACTOR_ONE_MINUS_CONSTANT_ALPHA = VK_BLEND_FACTOR_ONE_MINUS_CONSTANT_ALPHA,
  CRUDE_GFX_RHI_BLEND_FACTOR_SRC_ALPHA_SATURATE = VK_BLEND_FACTOR_SRC_ALPHA_SATURATE,
  CRUDE_GFX_RHI_BLEND_FACTOR_SRC1_COLOR = VK_BLEND_FACTOR_SRC1_COLOR,
  CRUDE_GFX_RHI_BLEND_FACTOR_ONE_MINUS_SRC1_COLOR = VK_BLEND_FACTOR_ONE_MINUS_SRC1_COLOR,
  CRUDE_GFX_RHI_BLEND_FACTOR_SRC1_ALPHA = VK_BLEND_FACTOR_SRC1_ALPHA,
  CRUDE_GFX_RHI_BLEND_FACTOR_ONE_MINUS_SRC1_ALPHA = VK_BLEND_FACTOR_ONE_MINUS_SRC1_ALPHA,
  CRUDE_GFX_RHI_BLEND_FACTOR_MAX_ENUM = VK_BLEND_FACTOR_MAX_ENUM
} crude_gfx_rhi_blend_factor;

typedef enum crude_gfx_rhi_blend_op
{
  CRUDE_GFX_RHI_BLEND_OP_ADD = VK_BLEND_OP_ADD,
  CRUDE_GFX_RHI_BLEND_OP_SUBTRACT = VK_BLEND_OP_SUBTRACT,
  CRUDE_GFX_RHI_BLEND_OP_REVERSE_SUBTRACT = VK_BLEND_OP_REVERSE_SUBTRACT,
  CRUDE_GFX_RHI_BLEND_OP_MIN = VK_BLEND_OP_MIN,
  CRUDE_GFX_RHI_BLEND_OP_MAX = VK_BLEND_OP_MAX,
  CRUDE_GFX_RHI_BLEND_OP_ZERO_EXT = VK_BLEND_OP_ZERO_EXT,
  CRUDE_GFX_RHI_BLEND_OP_SRC_EXT = VK_BLEND_OP_SRC_EXT,
  CRUDE_GFX_RHI_BLEND_OP_DST_EXT = VK_BLEND_OP_DST_EXT,
  CRUDE_GFX_RHI_BLEND_OP_SRC_OVER_EXT = VK_BLEND_OP_SRC_OVER_EXT,
  CRUDE_GFX_RHI_BLEND_OP_DST_OVER_EXT = VK_BLEND_OP_DST_OVER_EXT,
  CRUDE_GFX_RHI_BLEND_OP_SRC_IN_EXT = VK_BLEND_OP_SRC_IN_EXT,
  CRUDE_GFX_RHI_BLEND_OP_DST_IN_EXT = VK_BLEND_OP_DST_IN_EXT,
  CRUDE_GFX_RHI_BLEND_OP_SRC_OUT_EXT = VK_BLEND_OP_SRC_OUT_EXT,
  CRUDE_GFX_RHI_BLEND_OP_DST_OUT_EXT = VK_BLEND_OP_DST_OUT_EXT,
  CRUDE_GFX_RHI_BLEND_OP_SRC_ATOP_EXT = VK_BLEND_OP_SRC_ATOP_EXT,
  CRUDE_GFX_RHI_BLEND_OP_DST_ATOP_EXT = VK_BLEND_OP_DST_ATOP_EXT,
  CRUDE_GFX_RHI_BLEND_OP_XOR_EXT = VK_BLEND_OP_XOR_EXT,
  CRUDE_GFX_RHI_BLEND_OP_MULTIPLY_EXT = VK_BLEND_OP_MULTIPLY_EXT,
  CRUDE_GFX_RHI_BLEND_OP_SCREEN_EXT = VK_BLEND_OP_SCREEN_EXT,
  CRUDE_GFX_RHI_BLEND_OP_OVERLAY_EXT = VK_BLEND_OP_OVERLAY_EXT,
  CRUDE_GFX_RHI_BLEND_OP_DARKEN_EXT = VK_BLEND_OP_DARKEN_EXT,
  CRUDE_GFX_RHI_BLEND_OP_LIGHTEN_EXT = VK_BLEND_OP_LIGHTEN_EXT,
  CRUDE_GFX_RHI_BLEND_OP_COLORDODGE_EXT = VK_BLEND_OP_COLORDODGE_EXT,
  CRUDE_GFX_RHI_BLEND_OP_COLORBURN_EXT = VK_BLEND_OP_COLORBURN_EXT,
  CRUDE_GFX_RHI_BLEND_OP_HARDLIGHT_EXT = VK_BLEND_OP_HARDLIGHT_EXT,
  CRUDE_GFX_RHI_BLEND_OP_SOFTLIGHT_EXT = VK_BLEND_OP_SOFTLIGHT_EXT,
  CRUDE_GFX_RHI_BLEND_OP_DIFFERENCE_EXT = VK_BLEND_OP_DIFFERENCE_EXT,
  CRUDE_GFX_RHI_BLEND_OP_EXCLUSION_EXT = VK_BLEND_OP_EXCLUSION_EXT,
  CRUDE_GFX_RHI_BLEND_OP_INVERT_EXT = VK_BLEND_OP_INVERT_EXT,
  CRUDE_GFX_RHI_BLEND_OP_INVERT_RGB_EXT = VK_BLEND_OP_INVERT_RGB_EXT,
  CRUDE_GFX_RHI_BLEND_OP_LINEARDODGE_EXT = VK_BLEND_OP_LINEARDODGE_EXT,
  CRUDE_GFX_RHI_BLEND_OP_LINEARBURN_EXT = VK_BLEND_OP_LINEARBURN_EXT,
  CRUDE_GFX_RHI_BLEND_OP_VIVIDLIGHT_EXT = VK_BLEND_OP_VIVIDLIGHT_EXT,
  CRUDE_GFX_RHI_BLEND_OP_LINEARLIGHT_EXT = VK_BLEND_OP_LINEARLIGHT_EXT,
  CRUDE_GFX_RHI_BLEND_OP_PINLIGHT_EXT = VK_BLEND_OP_PINLIGHT_EXT,
  CRUDE_GFX_RHI_BLEND_OP_HARDMIX_EXT = VK_BLEND_OP_HARDMIX_EXT,
  CRUDE_GFX_RHI_BLEND_OP_HSL_HUE_EXT = VK_BLEND_OP_HSL_HUE_EXT,
  CRUDE_GFX_RHI_BLEND_OP_HSL_SATURATION_EXT = VK_BLEND_OP_HSL_SATURATION_EXT,
  CRUDE_GFX_RHI_BLEND_OP_HSL_COLOR_EXT = VK_BLEND_OP_HSL_COLOR_EXT,
  CRUDE_GFX_RHI_BLEND_OP_HSL_LUMINOSITY_EXT = VK_BLEND_OP_HSL_LUMINOSITY_EXT,
  CRUDE_GFX_RHI_BLEND_OP_PLUS_EXT = VK_BLEND_OP_PLUS_EXT,
  CRUDE_GFX_RHI_BLEND_OP_PLUS_CLAMPED_EXT = VK_BLEND_OP_PLUS_CLAMPED_EXT,
  CRUDE_GFX_RHI_BLEND_OP_PLUS_CLAMPED_ALPHA_EXT = VK_BLEND_OP_PLUS_CLAMPED_ALPHA_EXT,
  CRUDE_GFX_RHI_BLEND_OP_PLUS_DARKER_EXT = VK_BLEND_OP_PLUS_DARKER_EXT,
  CRUDE_GFX_RHI_BLEND_OP_MINUS_EXT = VK_BLEND_OP_MINUS_EXT,
  CRUDE_GFX_RHI_BLEND_OP_MINUS_CLAMPED_EXT = VK_BLEND_OP_MINUS_CLAMPED_EXT,
  CRUDE_GFX_RHI_BLEND_OP_CONTRAST_EXT = VK_BLEND_OP_CONTRAST_EXT,
  CRUDE_GFX_RHI_BLEND_OP_INVERT_OVG_EXT = VK_BLEND_OP_INVERT_OVG_EXT,
  CRUDE_GFX_RHI_BLEND_OP_RED_EXT = VK_BLEND_OP_RED_EXT,
  CRUDE_GFX_RHI_BLEND_OP_GREEN_EXT = VK_BLEND_OP_GREEN_EXT,
  CRUDE_GFX_RHI_BLEND_OP_BLUE_EXT = VK_BLEND_OP_BLUE_EXT,
  CRUDE_GFX_RHI_BLEND_OP_MAX_ENUM = VK_BLEND_OP_MAX_ENUM
} crude_gfx_rhi_blend_op;

typedef enum crude_gfx_rhi_filter
{
  CRUDE_GFX_RHI_FILTER_NEAREST = VK_FILTER_NEAREST,
  CRUDE_GFX_RHI_FILTER_LINEAR = VK_FILTER_LINEAR,
  CRUDE_GFX_RHI_FILTER_CUBIC_EXT = VK_FILTER_CUBIC_EXT,
  CRUDE_GFX_RHI_FILTER_CUBIC_IMG = VK_FILTER_CUBIC_IMG,
  CRUDE_GFX_RHI_FILTER_MAX_ENUM = VK_FILTER_MAX_ENUM
} crude_gfx_rhi_filter;

typedef enum crude_gfx_rhi_sampler_mipmap_mode
{
  CRUDE_GFX_RHI_SAMPLER_MIPMAP_MODE_NEAREST = VK_SAMPLER_MIPMAP_MODE_NEAREST,
  CRUDE_GFX_RHI_SAMPLER_MIPMAP_MODE_LINEAR = VK_SAMPLER_MIPMAP_MODE_LINEAR,
  CRUDE_GFX_RHI_SAMPLER_MIPMAP_MODE_MAX_ENUM = VK_SAMPLER_MIPMAP_MODE_MAX_ENUM
} crude_gfx_rhi_sampler_mipmap_mode;

typedef enum crude_gfx_rhi_sampler_address_mode
{
  CRUDE_GFX_RHI_SAMPLER_ADDRESS_MODE_REPEAT = VK_SAMPLER_ADDRESS_MODE_REPEAT,
  CRUDE_GFX_RHI_SAMPLER_ADDRESS_MODE_MIRRORED_REPEAT = VK_SAMPLER_ADDRESS_MODE_MIRRORED_REPEAT,
  CRUDE_GFX_RHI_SAMPLER_ADDRESS_MODE_CLAMP_TO_EDGE = VK_SAMPLER_ADDRESS_MODE_CLAMP_TO_EDGE,
  CRUDE_GFX_RHI_SAMPLER_ADDRESS_MODE_CLAMP_TO_BORDER = VK_SAMPLER_ADDRESS_MODE_CLAMP_TO_BORDER,
  CRUDE_GFX_RHI_SAMPLER_ADDRESS_MODE_MIRROR_CLAMP_TO_EDGE = VK_SAMPLER_ADDRESS_MODE_MIRROR_CLAMP_TO_EDGE,
  CRUDE_GFX_RHI_SAMPLER_ADDRESS_MODE_MIRROR_CLAMP_TO_EDGE_KHR = VK_SAMPLER_ADDRESS_MODE_MIRROR_CLAMP_TO_EDGE_KHR,
  CRUDE_GFX_RHI_SAMPLER_ADDRESS_MODE_MAX_ENUM = VK_SAMPLER_ADDRESS_MODE_MAX_ENUM
} crude_gfx_rhi_sampler_address_mode;

typedef enum crude_gfx_rhi_sampler_reduction_mode
{
} crude_gfx_rhi_sampler_reduction_mode;

typedef enum crude_gfx_rhi_image_layout
{
  CRUDE_GFX_RHI_IMAGE_LAYOUT_UNDEFINED = VK_IMAGE_LAYOUT_UNDEFINED,
  CRUDE_GFX_RHI_IMAGE_LAYOUT_GENERAL = VK_IMAGE_LAYOUT_GENERAL,
  CRUDE_GFX_RHI_IMAGE_LAYOUT_COLOR_ATTACHMENT_OPTIMAL = VK_IMAGE_LAYOUT_COLOR_ATTACHMENT_OPTIMAL,
  CRUDE_GFX_RHI_IMAGE_LAYOUT_DEPTH_STENCIL_ATTACHMENT_OPTIMAL = VK_IMAGE_LAYOUT_DEPTH_STENCIL_ATTACHMENT_OPTIMAL,
  CRUDE_GFX_RHI_IMAGE_LAYOUT_DEPTH_STENCIL_READ_ONLY_OPTIMAL = VK_IMAGE_LAYOUT_DEPTH_STENCIL_READ_ONLY_OPTIMAL,
  CRUDE_GFX_RHI_IMAGE_LAYOUT_SHADER_READ_ONLY_OPTIMAL = VK_IMAGE_LAYOUT_SHADER_READ_ONLY_OPTIMAL,
  CRUDE_GFX_RHI_IMAGE_LAYOUT_TRANSFER_SRC_OPTIMAL = VK_IMAGE_LAYOUT_TRANSFER_SRC_OPTIMAL,
  CRUDE_GFX_RHI_IMAGE_LAYOUT_TRANSFER_DST_OPTIMAL = VK_IMAGE_LAYOUT_TRANSFER_DST_OPTIMAL,
  CRUDE_GFX_RHI_IMAGE_LAYOUT_PREINITIALIZED = VK_IMAGE_LAYOUT_PREINITIALIZED,
  CRUDE_GFX_RHI_IMAGE_LAYOUT_DEPTH_READ_ONLY_STENCIL_ATTACHMENT_OPTIMAL = VK_IMAGE_LAYOUT_DEPTH_READ_ONLY_STENCIL_ATTACHMENT_OPTIMAL,
  CRUDE_GFX_RHI_IMAGE_LAYOUT_DEPTH_ATTACHMENT_STENCIL_READ_ONLY_OPTIMAL = VK_IMAGE_LAYOUT_DEPTH_ATTACHMENT_STENCIL_READ_ONLY_OPTIMAL,
  CRUDE_GFX_RHI_IMAGE_LAYOUT_DEPTH_ATTACHMENT_OPTIMAL = VK_IMAGE_LAYOUT_DEPTH_ATTACHMENT_OPTIMAL,
  CRUDE_GFX_RHI_IMAGE_LAYOUT_DEPTH_READ_ONLY_OPTIMAL = VK_IMAGE_LAYOUT_DEPTH_READ_ONLY_OPTIMAL,
  CRUDE_GFX_RHI_IMAGE_LAYOUT_STENCIL_ATTACHMENT_OPTIMAL = VK_IMAGE_LAYOUT_STENCIL_ATTACHMENT_OPTIMAL,
  CRUDE_GFX_RHI_IMAGE_LAYOUT_STENCIL_READ_ONLY_OPTIMAL = VK_IMAGE_LAYOUT_STENCIL_READ_ONLY_OPTIMAL,
  CRUDE_GFX_RHI_IMAGE_LAYOUT_READ_ONLY_OPTIMAL = VK_IMAGE_LAYOUT_READ_ONLY_OPTIMAL,
  CRUDE_GFX_RHI_IMAGE_LAYOUT_ATTACHMENT_OPTIMAL = VK_IMAGE_LAYOUT_ATTACHMENT_OPTIMAL,
  CRUDE_GFX_RHI_IMAGE_LAYOUT_RENDERING_LOCAL_READ = VK_IMAGE_LAYOUT_RENDERING_LOCAL_READ,
  CRUDE_GFX_RHI_IMAGE_LAYOUT_PRESENT_SRC_KHR = VK_IMAGE_LAYOUT_PRESENT_SRC_KHR,
  CRUDE_GFX_RHI_IMAGE_LAYOUT_VIDEO_DECODE_DST_KHR = VK_IMAGE_LAYOUT_VIDEO_DECODE_DST_KHR,
  CRUDE_GFX_RHI_IMAGE_LAYOUT_VIDEO_DECODE_SRC_KHR = VK_IMAGE_LAYOUT_VIDEO_DECODE_SRC_KHR,
  CRUDE_GFX_RHI_IMAGE_LAYOUT_VIDEO_DECODE_DPB_KHR = VK_IMAGE_LAYOUT_VIDEO_DECODE_DPB_KHR,
  CRUDE_GFX_RHI_IMAGE_LAYOUT_SHARED_PRESENT_KHR = VK_IMAGE_LAYOUT_SHARED_PRESENT_KHR,
  CRUDE_GFX_RHI_IMAGE_LAYOUT_FRAGMENT_DENSITY_MAP_OPTIMAL_EXT = VK_IMAGE_LAYOUT_FRAGMENT_DENSITY_MAP_OPTIMAL_EXT,
  CRUDE_GFX_RHI_IMAGE_LAYOUT_FRAGMENT_SHADING_RATE_ATTACHMENT_OPTIMAL_KHR = VK_IMAGE_LAYOUT_FRAGMENT_SHADING_RATE_ATTACHMENT_OPTIMAL_KHR,
  CRUDE_GFX_RHI_IMAGE_LAYOUT_VIDEO_ENCODE_DST_KHR = VK_IMAGE_LAYOUT_VIDEO_ENCODE_DST_KHR,
  CRUDE_GFX_RHI_IMAGE_LAYOUT_VIDEO_ENCODE_SRC_KHR = VK_IMAGE_LAYOUT_VIDEO_ENCODE_SRC_KHR,
  CRUDE_GFX_RHI_IMAGE_LAYOUT_VIDEO_ENCODE_DPB_KHR = VK_IMAGE_LAYOUT_VIDEO_ENCODE_DPB_KHR,
  CRUDE_GFX_RHI_IMAGE_LAYOUT_ATTACHMENT_FEEDBACK_LOOP_OPTIMAL_EXT = VK_IMAGE_LAYOUT_ATTACHMENT_FEEDBACK_LOOP_OPTIMAL_EXT,
  CRUDE_GFX_RHI_IMAGE_LAYOUT_TENSOR_ALIASING_ARM = VK_IMAGE_LAYOUT_TENSOR_ALIASING_ARM,
  CRUDE_GFX_RHI_IMAGE_LAYOUT_VIDEO_ENCODE_QUANTIZATION_MAP_KHR = VK_IMAGE_LAYOUT_VIDEO_ENCODE_QUANTIZATION_MAP_KHR,
  CRUDE_GFX_RHI_IMAGE_LAYOUT_ZERO_INITIALIZED_EXT = VK_IMAGE_LAYOUT_ZERO_INITIALIZED_EXT,
  CRUDE_GFX_RHI_IMAGE_LAYOUT_DEPTH_READ_ONLY_STENCIL_ATTACHMENT_OPTIMAL_KHR = VK_IMAGE_LAYOUT_DEPTH_READ_ONLY_STENCIL_ATTACHMENT_OPTIMAL_KHR,
  CRUDE_GFX_RHI_IMAGE_LAYOUT_DEPTH_ATTACHMENT_STENCIL_READ_ONLY_OPTIMAL_KHR = VK_IMAGE_LAYOUT_DEPTH_ATTACHMENT_STENCIL_READ_ONLY_OPTIMAL_KHR,
  CRUDE_GFX_RHI_IMAGE_LAYOUT_SHADING_RATE_OPTIMAL_NV = VK_IMAGE_LAYOUT_SHADING_RATE_OPTIMAL_NV,
  CRUDE_GFX_RHI_IMAGE_LAYOUT_RENDERING_LOCAL_READ_KHR = VK_IMAGE_LAYOUT_RENDERING_LOCAL_READ_KHR,
  CRUDE_GFX_RHI_IMAGE_LAYOUT_DEPTH_ATTACHMENT_OPTIMAL_KHR = VK_IMAGE_LAYOUT_DEPTH_ATTACHMENT_OPTIMAL_KHR,
  CRUDE_GFX_RHI_IMAGE_LAYOUT_DEPTH_READ_ONLY_OPTIMAL_KHR = VK_IMAGE_LAYOUT_DEPTH_READ_ONLY_OPTIMAL_KHR,
  CRUDE_GFX_RHI_IMAGE_LAYOUT_STENCIL_ATTACHMENT_OPTIMAL_KHR = VK_IMAGE_LAYOUT_STENCIL_ATTACHMENT_OPTIMAL_KHR,
  CRUDE_GFX_RHI_IMAGE_LAYOUT_STENCIL_READ_ONLY_OPTIMAL_KHR = VK_IMAGE_LAYOUT_STENCIL_READ_ONLY_OPTIMAL_KHR,
  CRUDE_GFX_RHI_IMAGE_LAYOUT_READ_ONLY_OPTIMAL_KHR = VK_IMAGE_LAYOUT_READ_ONLY_OPTIMAL_KHR,
  CRUDE_GFX_RHI_IMAGE_LAYOUT_ATTACHMENT_OPTIMAL_KHR = VK_IMAGE_LAYOUT_ATTACHMENT_OPTIMAL_KHR,
  CRUDE_GFX_RHI_IMAGE_LAYOUT_MAX_ENUM = VK_IMAGE_LAYOUT_MAX_ENUM
} crude_gfx_rhi_image_layout;

typedef enum crude_gfx_rhi_cull_mode_flags_bits
{
  CRUDE_GFX_RHI_CULL_MODE_NONE = VK_CULL_MODE_NONE,
  CRUDE_GFX_RHI_CULL_MODE_FRONT_BIT = VK_CULL_MODE_FRONT_BIT,
  CRUDE_GFX_RHI_CULL_MODE_BACK_BIT = VK_CULL_MODE_BACK_BIT,
  CRUDE_GFX_RHI_CULL_MODE_FRONT_AND_BACK = VK_CULL_MODE_FRONT_AND_BACK,
  CRUDE_GFX_RHI_CULL_MODE_FLAG_BITS_MAX_ENUM = VK_CULL_MODE_FLAG_BITS_MAX_ENUM
} crude_gfx_rhi_cull_mode_flags_bits;

typedef enum crude_gfx_rhi_front_face
{
  CRUDE_GFX_RHI_FRONT_FACE_COUNTER_CLOCKWISE = VK_FRONT_FACE_COUNTER_CLOCKWISE,
  CRUDE_GFX_RHI_FRONT_FACE_CLOCKWISE = VK_FRONT_FACE_CLOCKWISE,
  CRUDE_GFX_RHI_FRONT_FACE_MAX_ENUM = VK_FRONT_FACE_MAX_ENUM
} crude_gfx_rhi_front_face;

typedef enum crude_gfx_rhi_image_view_type
{
  CRUDE_GFX_RHI_IMAGE_VIEW_TYPE_1D = VK_IMAGE_VIEW_TYPE_1D,
  CRUDE_GFX_RHI_IMAGE_VIEW_TYPE_2D = VK_IMAGE_VIEW_TYPE_2D,
  CRUDE_GFX_RHI_IMAGE_VIEW_TYPE_3D = VK_IMAGE_VIEW_TYPE_3D,
  CRUDE_GFX_RHI_IMAGE_VIEW_TYPE_CUBE = VK_IMAGE_VIEW_TYPE_CUBE,
  CRUDE_GFX_RHI_IMAGE_VIEW_TYPE_1D_ARRAY = VK_IMAGE_VIEW_TYPE_1D_ARRAY,
  CRUDE_GFX_RHI_IMAGE_VIEW_TYPE_2D_ARRAY = VK_IMAGE_VIEW_TYPE_2D_ARRAY,
  CRUDE_GFX_RHI_IMAGE_VIEW_TYPE_CUBE_ARRAY = VK_IMAGE_VIEW_TYPE_CUBE_ARRAY,
  CRUDE_GFX_RHI_IMAGE_VIEW_TYPE_MAX_ENUM = VK_IMAGE_VIEW_TYPE_MAX_ENUM
} crude_gfx_rhi_image_view_type;

typedef enum crude_gfx_rhi_shader_stage_flag_bits
{
  CRUDE_GFX_RHI_SHADER_STAGE_VERTEX_BIT = VK_SHADER_STAGE_VERTEX_BIT,
  CRUDE_GFX_RHI_SHADER_STAGE_TESSELLATION_CONTROL_BIT = VK_SHADER_STAGE_TESSELLATION_CONTROL_BIT,
  CRUDE_GFX_RHI_SHADER_STAGE_TESSELLATION_EVALUATION_BIT = VK_SHADER_STAGE_TESSELLATION_EVALUATION_BIT,
  CRUDE_GFX_RHI_SHADER_STAGE_GEOMETRY_BIT = VK_SHADER_STAGE_GEOMETRY_BIT,
  CRUDE_GFX_RHI_SHADER_STAGE_FRAGMENT_BIT = VK_SHADER_STAGE_FRAGMENT_BIT,
  CRUDE_GFX_RHI_SHADER_STAGE_COMPUTE_BIT = VK_SHADER_STAGE_COMPUTE_BIT,
  CRUDE_GFX_RHI_SHADER_STAGE_ALL_GRAPHICS = VK_SHADER_STAGE_ALL_GRAPHICS,
  CRUDE_GFX_RHI_SHADER_STAGE_ALL = VK_SHADER_STAGE_ALL,
  CRUDE_GFX_RHI_SHADER_STAGE_RAYGEN_BIT_KHR = VK_SHADER_STAGE_RAYGEN_BIT_KHR,
  CRUDE_GFX_RHI_SHADER_STAGE_ANY_HIT_BIT_KHR = VK_SHADER_STAGE_ANY_HIT_BIT_KHR,
  CRUDE_GFX_RHI_SHADER_STAGE_CLOSEST_HIT_BIT_KHR = VK_SHADER_STAGE_CLOSEST_HIT_BIT_KHR,
  CRUDE_GFX_RHI_SHADER_STAGE_MISS_BIT_KHR = VK_SHADER_STAGE_MISS_BIT_KHR,
  CRUDE_GFX_RHI_SHADER_STAGE_INTERSECTION_BIT_KHR = VK_SHADER_STAGE_INTERSECTION_BIT_KHR,
  CRUDE_GFX_RHI_SHADER_STAGE_CALLABLE_BIT_KHR = VK_SHADER_STAGE_CALLABLE_BIT_KHR,
  CRUDE_GFX_RHI_SHADER_STAGE_TASK_BIT_EXT = VK_SHADER_STAGE_TASK_BIT_EXT,
  CRUDE_GFX_RHI_SHADER_STAGE_MESH_BIT_EXT = VK_SHADER_STAGE_MESH_BIT_EXT,
  CRUDE_GFX_RHI_SHADER_STAGE_SUBPASS_SHADING_BIT_HUAWEI = VK_SHADER_STAGE_SUBPASS_SHADING_BIT_HUAWEI,
  CRUDE_GFX_RHI_SHADER_STAGE_CLUSTER_CULLING_BIT_HUAWEI = VK_SHADER_STAGE_CLUSTER_CULLING_BIT_HUAWEI,
  CRUDE_GFX_RHI_SHADER_STAGE_RAYGEN_BIT_NV = VK_SHADER_STAGE_RAYGEN_BIT_NV,
  CRUDE_GFX_RHI_SHADER_STAGE_ANY_HIT_BIT_NV = VK_SHADER_STAGE_ANY_HIT_BIT_NV,
  CRUDE_GFX_RHI_SHADER_STAGE_CLOSEST_HIT_BIT_NV = VK_SHADER_STAGE_CLOSEST_HIT_BIT_NV,
  CRUDE_GFX_RHI_SHADER_STAGE_MISS_BIT_NV = VK_SHADER_STAGE_MISS_BIT_NV,
  CRUDE_GFX_RHI_SHADER_STAGE_INTERSECTION_BIT_NV = VK_SHADER_STAGE_INTERSECTION_BIT_NV,
  CRUDE_GFX_RHI_SHADER_STAGE_CALLABLE_BIT_NV = VK_SHADER_STAGE_CALLABLE_BIT_NV,
  CRUDE_GFX_RHI_SHADER_STAGE_TASK_BIT_NV = VK_SHADER_STAGE_TASK_BIT_NV,
  CRUDE_GFX_RHI_SHADER_STAGE_MESH_BIT_NV = VK_SHADER_STAGE_MESH_BIT_NV,
  CRUDE_GFX_RHI_SHADER_STAGE_FLAG_BITS_MAX_ENUM = VK_SHADER_STAGE_FLAG_BITS_MAX_ENUM
} crude_gfx_rhi_shader_stage_flag_bits;

typedef enum crude_gfx_rhi_descriptor_type
{
  CRUDE_GFX_RHI_DESCRIPTOR_TYPE_SAMPLER = VK_DESCRIPTOR_TYPE_SAMPLER,
  CRUDE_GFX_RHI_DESCRIPTOR_TYPE_COMBINED_IMAGE_SAMPLER = VK_DESCRIPTOR_TYPE_COMBINED_IMAGE_SAMPLER,
  CRUDE_GFX_RHI_DESCRIPTOR_TYPE_SAMPLED_IMAGE = VK_DESCRIPTOR_TYPE_SAMPLED_IMAGE,
  CRUDE_GFX_RHI_DESCRIPTOR_TYPE_STORAGE_IMAGE = VK_DESCRIPTOR_TYPE_STORAGE_IMAGE,
  CRUDE_GFX_RHI_DESCRIPTOR_TYPE_UNIFORM_TEXEL_BUFFER = VK_DESCRIPTOR_TYPE_UNIFORM_TEXEL_BUFFER,
  CRUDE_GFX_RHI_DESCRIPTOR_TYPE_STORAGE_TEXEL_BUFFER = VK_DESCRIPTOR_TYPE_STORAGE_TEXEL_BUFFER,
  CRUDE_GFX_RHI_DESCRIPTOR_TYPE_UNIFORM_BUFFER = VK_DESCRIPTOR_TYPE_UNIFORM_BUFFER,
  CRUDE_GFX_RHI_DESCRIPTOR_TYPE_STORAGE_BUFFER = VK_DESCRIPTOR_TYPE_STORAGE_BUFFER,
  CRUDE_GFX_RHI_DESCRIPTOR_TYPE_UNIFORM_BUFFER_DYNAMIC = VK_DESCRIPTOR_TYPE_UNIFORM_BUFFER_DYNAMIC,
  CRUDE_GFX_RHI_DESCRIPTOR_TYPE_STORAGE_BUFFER_DYNAMIC = VK_DESCRIPTOR_TYPE_STORAGE_BUFFER_DYNAMIC,
  CRUDE_GFX_RHI_DESCRIPTOR_TYPE_INPUT_ATTACHMENT = VK_DESCRIPTOR_TYPE_INPUT_ATTACHMENT,
  CRUDE_GFX_RHI_DESCRIPTOR_TYPE_INLINE_UNIFORM_BLOCK = VK_DESCRIPTOR_TYPE_INLINE_UNIFORM_BLOCK,
  CRUDE_GFX_RHI_DESCRIPTOR_TYPE_ACCELERATION_STRUCTURE_KHR = VK_DESCRIPTOR_TYPE_ACCELERATION_STRUCTURE_KHR,
  CRUDE_GFX_RHI_DESCRIPTOR_TYPE_ACCELERATION_STRUCTURE_NV = VK_DESCRIPTOR_TYPE_ACCELERATION_STRUCTURE_NV,
  CRUDE_GFX_RHI_DESCRIPTOR_TYPE_SAMPLE_WEIGHT_IMAGE_QCOM = VK_DESCRIPTOR_TYPE_SAMPLE_WEIGHT_IMAGE_QCOM,
  CRUDE_GFX_RHI_DESCRIPTOR_TYPE_BLOCK_MATCH_IMAGE_QCOM = VK_DESCRIPTOR_TYPE_BLOCK_MATCH_IMAGE_QCOM,
  CRUDE_GFX_RHI_DESCRIPTOR_TYPE_TENSOR_ARM = VK_DESCRIPTOR_TYPE_TENSOR_ARM,
  CRUDE_GFX_RHI_DESCRIPTOR_TYPE_MUTABLE_EXT = VK_DESCRIPTOR_TYPE_MUTABLE_EXT,
  CRUDE_GFX_RHI_DESCRIPTOR_TYPE_PARTITIONED_ACCELERATION_STRUCTURE_NV = VK_DESCRIPTOR_TYPE_PARTITIONED_ACCELERATION_STRUCTURE_NV,
  CRUDE_GFX_RHI_DESCRIPTOR_TYPE_INLINE_UNIFORM_BLOCK_EXT = VK_DESCRIPTOR_TYPE_INLINE_UNIFORM_BLOCK_EXT,
  CRUDE_GFX_RHI_DESCRIPTOR_TYPE_MUTABLE_VALVE = VK_DESCRIPTOR_TYPE_MUTABLE_VALVE,
  CRUDE_GFX_RHI_DESCRIPTOR_TYPE_MAX_ENUM = VK_DESCRIPTOR_TYPE_MAX_ENUM
} crude_gfx_rhi_descriptor_type;

typedef enum crude_gfx_rhi_primitive_topology
{
  CRUDE_GFX_RHI_PRIMITIVE_TOPOLOGY_POINT_LIST = VK_PRIMITIVE_TOPOLOGY_POINT_LIST,
  CRUDE_GFX_RHI_PRIMITIVE_TOPOLOGY_LINE_LIST = VK_PRIMITIVE_TOPOLOGY_LINE_LIST,
  CRUDE_GFX_RHI_PRIMITIVE_TOPOLOGY_LINE_STRIP = VK_PRIMITIVE_TOPOLOGY_LINE_STRIP,
  CRUDE_GFX_RHI_PRIMITIVE_TOPOLOGY_TRIANGLE_LIST = VK_PRIMITIVE_TOPOLOGY_TRIANGLE_LIST,
  CRUDE_GFX_RHI_PRIMITIVE_TOPOLOGY_TRIANGLE_STRIP = VK_PRIMITIVE_TOPOLOGY_TRIANGLE_STRIP,
  CRUDE_GFX_RHI_PRIMITIVE_TOPOLOGY_TRIANGLE_FAN = VK_PRIMITIVE_TOPOLOGY_TRIANGLE_FAN,
  CRUDE_GFX_RHI_PRIMITIVE_TOPOLOGY_LINE_LIST_WITH_ADJACENCY = VK_PRIMITIVE_TOPOLOGY_LINE_LIST_WITH_ADJACENCY,
  CRUDE_GFX_RHI_PRIMITIVE_TOPOLOGY_LINE_STRIP_WITH_ADJACENCY = VK_PRIMITIVE_TOPOLOGY_LINE_STRIP_WITH_ADJACENCY,
  CRUDE_GFX_RHI_PRIMITIVE_TOPOLOGY_TRIANGLE_LIST_WITH_ADJACENCY = VK_PRIMITIVE_TOPOLOGY_TRIANGLE_LIST_WITH_ADJACENCY,
  CRUDE_GFX_RHI_PRIMITIVE_TOPOLOGY_TRIANGLE_STRIP_WITH_ADJACENCY = VK_PRIMITIVE_TOPOLOGY_TRIANGLE_STRIP_WITH_ADJACENCY,
  CRUDE_GFX_RHI_PRIMITIVE_TOPOLOGY_PATCH_LIST = VK_PRIMITIVE_TOPOLOGY_PATCH_LIST,
  CRUDE_GFX_RHI_PRIMITIVE_TOPOLOGY_MAX_ENUM = VK_PRIMITIVE_TOPOLOGY_MAX_ENUM
} crude_gfx_rhi_primitive_topology;

typedef enum crude_gfx_rhi_image_type
{
  CRUDE_GFX_RHI_IMAGE_TYPE_1D = VK_IMAGE_TYPE_1D,
  CRUDE_GFX_RHI_IMAGE_TYPE_2D = VK_IMAGE_TYPE_2D,
  CRUDE_GFX_RHI_IMAGE_TYPE_3D = VK_IMAGE_TYPE_3D,
  CRUDE_GFX_RHI_IMAGE_TYPE_MAX_ENUM = VK_IMAGE_TYPE_MAX_ENUM
} crude_gfx_rhi_image_type;

typedef enum crude_gfx_rhi_color_space
{
  CRUDE_GFX_RHI_COLOR_SPACE_SRGB_NONLINEAR_KHR = VK_COLOR_SPACE_SRGB_NONLINEAR_KHR,
  CRUDE_GFX_RHI_COLOR_SPACE_DISPLAY_P3_NONLINEAR_EXT = VK_COLOR_SPACE_DISPLAY_P3_NONLINEAR_EXT,
  CRUDE_GFX_RHI_COLOR_SPACE_EXTENDED_SRGB_LINEAR_EXT = VK_COLOR_SPACE_EXTENDED_SRGB_LINEAR_EXT,
  CRUDE_GFX_RHI_COLOR_SPACE_DISPLAY_P3_LINEAR_EXT = VK_COLOR_SPACE_DISPLAY_P3_LINEAR_EXT,
  CRUDE_GFX_RHI_COLOR_SPACE_DCI_P3_NONLINEAR_EXT = VK_COLOR_SPACE_DCI_P3_NONLINEAR_EXT,
  CRUDE_GFX_RHI_COLOR_SPACE_BT709_LINEAR_EXT = VK_COLOR_SPACE_BT709_LINEAR_EXT,
  CRUDE_GFX_RHI_COLOR_SPACE_BT709_NONLINEAR_EXT = VK_COLOR_SPACE_BT709_NONLINEAR_EXT,
  CRUDE_GFX_RHI_COLOR_SPACE_BT2020_LINEAR_EXT = VK_COLOR_SPACE_BT2020_LINEAR_EXT,
  CRUDE_GFX_RHI_COLOR_SPACE_HDR10_ST2084_EXT = VK_COLOR_SPACE_HDR10_ST2084_EXT,
  CRUDE_GFX_RHI_COLOR_SPACE_DOLBYVISION_EXT = VK_COLOR_SPACE_DOLBYVISION_EXT,
  CRUDE_GFX_RHI_COLOR_SPACE_HDR10_HLG_EXT = VK_COLOR_SPACE_HDR10_HLG_EXT,
  CRUDE_GFX_RHI_COLOR_SPACE_ADOBERGB_LINEAR_EXT = VK_COLOR_SPACE_ADOBERGB_LINEAR_EXT,
  CRUDE_GFX_RHI_COLOR_SPACE_ADOBERGB_NONLINEAR_EXT = VK_COLOR_SPACE_ADOBERGB_NONLINEAR_EXT,
  CRUDE_GFX_RHI_COLOR_SPACE_PASS_THROUGH_EXT = VK_COLOR_SPACE_PASS_THROUGH_EXT,
  CRUDE_GFX_RHI_COLOR_SPACE_EXTENDED_SRGB_NONLINEAR_EXT = VK_COLOR_SPACE_EXTENDED_SRGB_NONLINEAR_EXT,
  CRUDE_GFX_RHI_COLOR_SPACE_DISPLAY_NATIVE_AMD = VK_COLOR_SPACE_DISPLAY_NATIVE_AMD,
  CRUDE_GFX_COLORSPACE_SRGB_NONLINEAR_KHR = VK_COLORSPACE_SRGB_NONLINEAR_KHR,
  CRUDE_GFX_RHI_COLOR_SPACE_DCI_P3_LINEAR_EXT = VK_COLOR_SPACE_DCI_P3_LINEAR_EXT,
  CRUDE_GFX_RHI_COLOR_SPACE_MAX_ENUM_KHR = VK_COLOR_SPACE_MAX_ENUM_KHR
} crude_gfx_rhi_color_space;

typedef struct crude_gfx_rhi_surface_format
{
  crude_gfx_rhi_format                                         format;
  crude_gfx_rhi_color_space                                    color_space;
} crude_gfx_rhi_surface_format;

typedef VkBufferUsageFlags2 crude_gfx_rhi_buffer_usage_flags;
typedef VkAccessFlags2 crude_gfx_rhi_access_flags;
typedef VkPipelineStageFlags2 crude_gfx_rhi_pipeline_stage_flags;

CRUDE_API bool
crude_gfx_rhi_format_has_depth_or_stencil
( 
  _In_ crude_gfx_rhi_format                                    value
);

CRUDE_API bool
crude_gfx_rhi_format_has_depth
( 
  _In_ crude_gfx_rhi_format                                    value
);

CRUDE_API crude_gfx_rhi_blend_factor
crude_gfx_rhi_string_to_blend_factor
(
  _In_ char const                                         *factor
);

CRUDE_API crude_gfx_rhi_blend_op
crude_gfx_rhi_string_to_blend_op
(
  _In_ char const                                         *op
);

#elif CRUDE_GFX_NAPI
typedef enum crude_gfx_rhi_format
{
  CRUDE_GFX_RHI_FORMAT_UNDEFINED,
  CRUDE_GFX_RHI_FORMAT_R4G4_UNORM_PACK8,
  CRUDE_GFX_RHI_FORMAT_R4G4B4A4_UNORM_PACK16,
  CRUDE_GFX_RHI_FORMAT_B4G4R4A4_UNORM_PACK16,
  CRUDE_GFX_RHI_FORMAT_R5G6B5_UNORM_PACK16,
  CRUDE_GFX_RHI_FORMAT_B5G6R5_UNORM_PACK16,
  CRUDE_GFX_RHI_FORMAT_R5G5B5A1_UNORM_PACK16,
  CRUDE_GFX_RHI_FORMAT_B5G5R5A1_UNORM_PACK16,
  CRUDE_GFX_RHI_FORMAT_A1R5G5B5_UNORM_PACK16,
  CRUDE_GFX_RHI_FORMAT_R8_UNORM,
  CRUDE_GFX_RHI_FORMAT_R8_SNORM,
  CRUDE_GFX_RHI_FORMAT_R8_USCALED,
  CRUDE_GFX_RHI_FORMAT_R8_SSCALED,
  CRUDE_GFX_RHI_FORMAT_R8_UINT,
  CRUDE_GFX_RHI_FORMAT_R8_SINT,
  CRUDE_GFX_RHI_FORMAT_R8_SRGB,
  CRUDE_GFX_RHI_FORMAT_R8G8_UNORM,
  CRUDE_GFX_RHI_FORMAT_R8G8_SNORM,
  CRUDE_GFX_RHI_FORMAT_R8G8_USCALED,
  CRUDE_GFX_RHI_FORMAT_R8G8_SSCALED,
  CRUDE_GFX_RHI_FORMAT_R8G8_UINT,
  CRUDE_GFX_RHI_FORMAT_R8G8_SINT,
  CRUDE_GFX_RHI_FORMAT_R8G8_SRGB,
  CRUDE_GFX_RHI_FORMAT_R8G8B8_UNORM,
  CRUDE_GFX_RHI_FORMAT_R8G8B8_SNORM,
  CRUDE_GFX_RHI_FORMAT_R8G8B8_USCALED,
  CRUDE_GFX_RHI_FORMAT_R8G8B8_SSCALED,
  CRUDE_GFX_RHI_FORMAT_R8G8B8_UINT,
  CRUDE_GFX_RHI_FORMAT_R8G8B8_SINT,
  CRUDE_GFX_RHI_FORMAT_R8G8B8_SRGB,
  CRUDE_GFX_RHI_FORMAT_B8G8R8_UNORM,
  CRUDE_GFX_RHI_FORMAT_B8G8R8_SNORM,
  CRUDE_GFX_RHI_FORMAT_B8G8R8_USCALED,
  CRUDE_GFX_RHI_FORMAT_B8G8R8_SSCALED,
  CRUDE_GFX_RHI_FORMAT_B8G8R8_UINT,
  CRUDE_GFX_RHI_FORMAT_B8G8R8_SINT,
  CRUDE_GFX_RHI_FORMAT_B8G8R8_SRGB,
  CRUDE_GFX_RHI_FORMAT_R8G8B8A8_UNORM,
  CRUDE_GFX_RHI_FORMAT_R8G8B8A8_SNORM,
  CRUDE_GFX_RHI_FORMAT_R8G8B8A8_USCALED,
  CRUDE_GFX_RHI_FORMAT_R8G8B8A8_SSCALED,
  CRUDE_GFX_RHI_FORMAT_R8G8B8A8_UINT,
  CRUDE_GFX_RHI_FORMAT_R8G8B8A8_SINT,
  CRUDE_GFX_RHI_FORMAT_R8G8B8A8_SRGB,
  CRUDE_GFX_RHI_FORMAT_B8G8R8A8_UNORM,
  CRUDE_GFX_RHI_FORMAT_B8G8R8A8_SNORM,
  CRUDE_GFX_RHI_FORMAT_B8G8R8A8_USCALED,
  CRUDE_GFX_RHI_FORMAT_B8G8R8A8_SSCALED,
  CRUDE_GFX_RHI_FORMAT_B8G8R8A8_UINT,
  CRUDE_GFX_RHI_FORMAT_B8G8R8A8_SINT,
  CRUDE_GFX_RHI_FORMAT_B8G8R8A8_SRGB,
  CRUDE_GFX_RHI_FORMAT_A8B8G8R8_UNORM_PACK32,
  CRUDE_GFX_RHI_FORMAT_A8B8G8R8_SNORM_PACK32,
  CRUDE_GFX_RHI_FORMAT_A8B8G8R8_USCALED_PACK32,
  CRUDE_GFX_RHI_FORMAT_A8B8G8R8_SSCALED_PACK32,
  CRUDE_GFX_RHI_FORMAT_A8B8G8R8_UINT_PACK32,
  CRUDE_GFX_RHI_FORMAT_A8B8G8R8_SINT_PACK32,
  CRUDE_GFX_RHI_FORMAT_A8B8G8R8_SRGB_PACK32,
  CRUDE_GFX_RHI_FORMAT_A2R10G10B10_UNORM_PACK32,
  CRUDE_GFX_RHI_FORMAT_A2R10G10B10_SNORM_PACK32,
  CRUDE_GFX_RHI_FORMAT_A2R10G10B10_USCALED_PACK32,
  CRUDE_GFX_RHI_FORMAT_A2R10G10B10_SSCALED_PACK32,
  CRUDE_GFX_RHI_FORMAT_A2R10G10B10_UINT_PACK32,
  CRUDE_GFX_RHI_FORMAT_A2R10G10B10_SINT_PACK32,
  CRUDE_GFX_RHI_FORMAT_A2B10G10R10_UNORM_PACK32,
  CRUDE_GFX_RHI_FORMAT_A2B10G10R10_SNORM_PACK32,
  CRUDE_GFX_RHI_FORMAT_A2B10G10R10_USCALED_PACK32,
  CRUDE_GFX_RHI_FORMAT_A2B10G10R10_SSCALED_PACK32,
  CRUDE_GFX_RHI_FORMAT_A2B10G10R10_UINT_PACK32,
  CRUDE_GFX_RHI_FORMAT_A2B10G10R10_SINT_PACK32,
  CRUDE_GFX_RHI_FORMAT_R16_UNORM,
  CRUDE_GFX_RHI_FORMAT_R16_SNORM,
  CRUDE_GFX_RHI_FORMAT_R16_USCALED,
  CRUDE_GFX_RHI_FORMAT_R16_SSCALED,
  CRUDE_GFX_RHI_FORMAT_R16_UINT,
  CRUDE_GFX_RHI_FORMAT_R16_SINT,
  CRUDE_GFX_RHI_FORMAT_R16_SFLOAT,
  CRUDE_GFX_RHI_FORMAT_R16G16_UNORM,
  CRUDE_GFX_RHI_FORMAT_R16G16_SNORM,
  CRUDE_GFX_RHI_FORMAT_R16G16_USCALED,
  CRUDE_GFX_RHI_FORMAT_R16G16_SSCALED,
  CRUDE_GFX_RHI_FORMAT_R16G16_UINT,
  CRUDE_GFX_RHI_FORMAT_R16G16_SINT,
  CRUDE_GFX_RHI_FORMAT_R16G16_SFLOAT,
  CRUDE_GFX_RHI_FORMAT_R16G16B16_UNORM,
  CRUDE_GFX_RHI_FORMAT_R16G16B16_SNORM,
  CRUDE_GFX_RHI_FORMAT_R16G16B16_USCALED,
  CRUDE_GFX_RHI_FORMAT_R16G16B16_SSCALED,
  CRUDE_GFX_RHI_FORMAT_R16G16B16_UINT,
  CRUDE_GFX_RHI_FORMAT_R16G16B16_SINT,
  CRUDE_GFX_RHI_FORMAT_R16G16B16_SFLOAT,
  CRUDE_GFX_RHI_FORMAT_R16G16B16A16_UNORM,
  CRUDE_GFX_RHI_FORMAT_R16G16B16A16_SNORM,
  CRUDE_GFX_RHI_FORMAT_R16G16B16A16_USCALED,
  CRUDE_GFX_RHI_FORMAT_R16G16B16A16_SSCALED,
  CRUDE_GFX_RHI_FORMAT_R16G16B16A16_UINT,
  CRUDE_GFX_RHI_FORMAT_R16G16B16A16_SINT,
  CRUDE_GFX_RHI_FORMAT_R16G16B16A16_SFLOAT,
  CRUDE_GFX_RHI_FORMAT_R32_UINT,
  CRUDE_GFX_RHI_FORMAT_R32_SINT,
  CRUDE_GFX_RHI_FORMAT_R32_SFLOAT,
  CRUDE_GFX_RHI_FORMAT_R32G32_UINT,
  CRUDE_GFX_RHI_FORMAT_R32G32_SINT,
  CRUDE_GFX_RHI_FORMAT_R32G32_SFLOAT,
  CRUDE_GFX_RHI_FORMAT_R32G32B32_UINT,
  CRUDE_GFX_RHI_FORMAT_R32G32B32_SINT,
  CRUDE_GFX_RHI_FORMAT_R32G32B32_SFLOAT,
  CRUDE_GFX_RHI_FORMAT_R32G32B32A32_UINT,
  CRUDE_GFX_RHI_FORMAT_R32G32B32A32_SINT,
  CRUDE_GFX_RHI_FORMAT_R32G32B32A32_SFLOAT,
  CRUDE_GFX_RHI_FORMAT_R64_UINT,
  CRUDE_GFX_RHI_FORMAT_R64_SINT,
  CRUDE_GFX_RHI_FORMAT_R64_SFLOAT,
  CRUDE_GFX_RHI_FORMAT_R64G64_UINT,
  CRUDE_GFX_RHI_FORMAT_R64G64_SINT,
  CRUDE_GFX_RHI_FORMAT_R64G64_SFLOAT,
  CRUDE_GFX_RHI_FORMAT_R64G64B64_UINT,
  CRUDE_GFX_RHI_FORMAT_R64G64B64_SINT,
  CRUDE_GFX_RHI_FORMAT_R64G64B64_SFLOAT,
  CRUDE_GFX_RHI_FORMAT_R64G64B64A64_UINT,
  CRUDE_GFX_RHI_FORMAT_R64G64B64A64_SINT,
  CRUDE_GFX_RHI_FORMAT_R64G64B64A64_SFLOAT,
  CRUDE_GFX_RHI_FORMAT_B10G11R11_UFLOAT_PACK32,
  CRUDE_GFX_RHI_FORMAT_E5B9G9R9_UFLOAT_PACK32,
  CRUDE_GFX_RHI_FORMAT_D16_UNORM,
  CRUDE_GFX_RHI_FORMAT_X8_D24_UNORM_PACK32,
  CRUDE_GFX_RHI_FORMAT_D32_SFLOAT,
  CRUDE_GFX_RHI_FORMAT_S8_UINT,
  CRUDE_GFX_RHI_FORMAT_D16_UNORM_S8_UINT,
  CRUDE_GFX_RHI_FORMAT_D24_UNORM_S8_UINT,
  CRUDE_GFX_RHI_FORMAT_D32_SFLOAT_S8_UINT,
} crude_gfx_rhi_format;

typedef enum crude_gfx_rhi_stencil_op
{
} crude_gfx_rhi_stencil_op;

typedef enum crude_gfx_rhi_compare_op
{
  CRUDE_GFX_RHI_COMPARE_OP_NEVER,
  CRUDE_GFX_RHI_COMPARE_OP_LESS,
  CRUDE_GFX_RHI_COMPARE_OP_EQUAL,
  CRUDE_GFX_RHI_COMPARE_OP_LESS_OR_EQUAL,
  CRUDE_GFX_RHI_COMPARE_OP_GREATER,
  CRUDE_GFX_RHI_COMPARE_OP_NOT_EQUAL,
  CRUDE_GFX_RHI_COMPARE_OP_GREATER_OR_EQUAL,
  CRUDE_GFX_RHI_COMPARE_OP_ALWAYS,
  CRUDE_GFX_RHI_COMPARE_OP_MAX_ENUM,
} crude_gfx_rhi_compare_op;

typedef enum crude_gfx_rhi_blend_factor
{
  CRUDE_GFX_RHI_BLEND_FACTOR_ZERO,
  CRUDE_GFX_RHI_BLEND_FACTOR_ONE,
  CRUDE_GFX_RHI_BLEND_FACTOR_SRC_COLOR,
  CRUDE_GFX_RHI_BLEND_FACTOR_ONE_MINUS_SRC_COLOR,
  CRUDE_GFX_RHI_BLEND_FACTOR_DST_COLOR,
  CRUDE_GFX_RHI_BLEND_FACTOR_ONE_MINUS_DST_COLOR,
  CRUDE_GFX_RHI_BLEND_FACTOR_SRC_ALPHA,
  CRUDE_GFX_RHI_BLEND_FACTOR_ONE_MINUS_SRC_ALPHA,
  CRUDE_GFX_RHI_BLEND_FACTOR_DST_ALPHA,
  CRUDE_GFX_RHI_BLEND_FACTOR_ONE_MINUS_DST_ALPHA,
  CRUDE_GFX_RHI_BLEND_FACTOR_CONSTANT_COLOR,
  CRUDE_GFX_RHI_BLEND_FACTOR_ONE_MINUS_CONSTANT_COLOR,
  CRUDE_GFX_RHI_BLEND_FACTOR_CONSTANT_ALPHA,
  CRUDE_GFX_RHI_BLEND_FACTOR_ONE_MINUS_CONSTANT_ALPHA,
  CRUDE_GFX_RHI_BLEND_FACTOR_SRC_ALPHA_SATURATE,
  CRUDE_GFX_RHI_BLEND_FACTOR_SRC1_COLOR,
  CRUDE_GFX_RHI_BLEND_FACTOR_ONE_MINUS_SRC1_COLOR,
  CRUDE_GFX_RHI_BLEND_FACTOR_SRC1_ALPHA,
  CRUDE_GFX_RHI_BLEND_FACTOR_ONE_MINUS_SRC1_ALPHA,
  CRUDE_GFX_RHI_BLEND_FACTOR_MAX_ENUM,
} crude_gfx_rhi_blend_factor;

typedef enum crude_gfx_rhi_blend_op
{
  CRUDE_GFX_RHI_BLEND_OP_ADD,
  CRUDE_GFX_RHI_BLEND_OP_SUBTRACT,
  CRUDE_GFX_RHI_BLEND_OP_REVERSE_SUBTRACT,
  CRUDE_GFX_RHI_BLEND_OP_MIN,
  CRUDE_GFX_RHI_BLEND_OP_MAX,
  CRUDE_GFX_RHI_BLEND_OP_ZERO_EXT,
  CRUDE_GFX_RHI_BLEND_OP_SRC_EXT,
  CRUDE_GFX_RHI_BLEND_OP_DST_EXT,
  CRUDE_GFX_RHI_BLEND_OP_SRC_OVER_EXT,
  CRUDE_GFX_RHI_BLEND_OP_DST_OVER_EXT,
  CRUDE_GFX_RHI_BLEND_OP_SRC_IN_EXT,
  CRUDE_GFX_RHI_BLEND_OP_DST_IN_EXT,
  CRUDE_GFX_RHI_BLEND_OP_SRC_OUT_EXT,
  CRUDE_GFX_RHI_BLEND_OP_DST_OUT_EXT,
  CRUDE_GFX_RHI_BLEND_OP_SRC_ATOP_EXT,
  CRUDE_GFX_RHI_BLEND_OP_DST_ATOP_EXT,
  CRUDE_GFX_RHI_BLEND_OP_XOR_EXT,
  CRUDE_GFX_RHI_BLEND_OP_MULTIPLY_EXT,
  CRUDE_GFX_RHI_BLEND_OP_SCREEN_EXT,
  CRUDE_GFX_RHI_BLEND_OP_OVERLAY_EXT,
  CRUDE_GFX_RHI_BLEND_OP_DARKEN_EXT,
  CRUDE_GFX_RHI_BLEND_OP_LIGHTEN_EXT,
  CRUDE_GFX_RHI_BLEND_OP_COLORDODGE_EXT,
  CRUDE_GFX_RHI_BLEND_OP_COLORBURN_EXT,
  CRUDE_GFX_RHI_BLEND_OP_HARDLIGHT_EXT,
  CRUDE_GFX_RHI_BLEND_OP_SOFTLIGHT_EXT,
  CRUDE_GFX_RHI_BLEND_OP_DIFFERENCE_EXT,
  CRUDE_GFX_RHI_BLEND_OP_EXCLUSION_EXT,
  CRUDE_GFX_RHI_BLEND_OP_INVERT_EXT,
  CRUDE_GFX_RHI_BLEND_OP_INVERT_RGB_EXT,
  CRUDE_GFX_RHI_BLEND_OP_LINEARDODGE_EXT,
  CRUDE_GFX_RHI_BLEND_OP_LINEARBURN_EXT,
  CRUDE_GFX_RHI_BLEND_OP_VIVIDLIGHT_EXT,
  CRUDE_GFX_RHI_BLEND_OP_LINEARLIGHT_EXT,
  CRUDE_GFX_RHI_BLEND_OP_PINLIGHT_EXT,
  CRUDE_GFX_RHI_BLEND_OP_HARDMIX_EXT,
  CRUDE_GFX_RHI_BLEND_OP_HSL_HUE_EXT,
  CRUDE_GFX_RHI_BLEND_OP_HSL_SATURATION_EXT,
  CRUDE_GFX_RHI_BLEND_OP_HSL_COLOR_EXT,
  CRUDE_GFX_RHI_BLEND_OP_HSL_LUMINOSITY_EXT,
  CRUDE_GFX_RHI_BLEND_OP_PLUS_EXT,
  CRUDE_GFX_RHI_BLEND_OP_PLUS_CLAMPED_EXT,
  CRUDE_GFX_RHI_BLEND_OP_PLUS_CLAMPED_ALPHA_EXT,
  CRUDE_GFX_RHI_BLEND_OP_PLUS_DARKER_EXT,
  CRUDE_GFX_RHI_BLEND_OP_MINUS_EXT,
  CRUDE_GFX_RHI_BLEND_OP_MINUS_CLAMPED_EXT,
  CRUDE_GFX_RHI_BLEND_OP_CONTRAST_EXT,
  CRUDE_GFX_RHI_BLEND_OP_INVERT_OVG_EXT,
  CRUDE_GFX_RHI_BLEND_OP_RED_EXT,
  CRUDE_GFX_RHI_BLEND_OP_GREEN_EXT,
  CRUDE_GFX_RHI_BLEND_OP_BLUE_EXT,
  CRUDE_GFX_RHI_BLEND_OP_MAX_ENUM,
} crude_gfx_rhi_blend_op;

typedef enum crude_gfx_rhi_filter
{
  CRUDE_GFX_RHI_FILTER_NEAREST,
  CRUDE_GFX_RHI_FILTER_LINEAR,
  CRUDE_GFX_RHI_FILTER_CUBIC_EXT,
  CRUDE_GFX_RHI_FILTER_CUBIC_IMG,
  CRUDE_GFX_RHI_FILTER_MAX_ENUM,
} crude_gfx_rhi_filter;

typedef enum crude_gfx_rhi_sampler_mipmap_mode
{
  CRUDE_GFX_RHI_SAMPLER_MIPMAP_MODE_NEAREST,
  CRUDE_GFX_RHI_SAMPLER_MIPMAP_MODE_LINEAR,
  CRUDE_GFX_RHI_SAMPLER_MIPMAP_MODE_MAX_ENUM,
} crude_gfx_rhi_sampler_mipmap_mode;

typedef enum crude_gfx_rhi_sampler_address_mode
{
  CRUDE_GFX_RHI_SAMPLER_ADDRESS_MODE_REPEAT,
  CRUDE_GFX_RHI_SAMPLER_ADDRESS_MODE_MIRRORED_REPEAT,
  CRUDE_GFX_RHI_SAMPLER_ADDRESS_MODE_CLAMP_TO_EDGE,
  CRUDE_GFX_RHI_SAMPLER_ADDRESS_MODE_CLAMP_TO_BORDER,
  CRUDE_GFX_RHI_SAMPLER_ADDRESS_MODE_MIRROR_CLAMP_TO_EDGE,
  CRUDE_GFX_RHI_SAMPLER_ADDRESS_MODE_MIRROR_CLAMP_TO_EDGE_KHR,
  CRUDE_GFX_RHI_SAMPLER_ADDRESS_MODE_MAX_ENUM,
} crude_gfx_rhi_sampler_address_mode;

typedef enum crude_gfx_rhi_sampler_reduction_mode
{
} crude_gfx_rhi_sampler_reduction_mode;

typedef enum crude_gfx_rhi_image_layout
{
  CRUDE_GFX_RHI_IMAGE_LAYOUT_UNDEFINED,
  CRUDE_GFX_RHI_IMAGE_LAYOUT_GENERAL,
  CRUDE_GFX_RHI_IMAGE_LAYOUT_COLOR_ATTACHMENT_OPTIMAL,
  CRUDE_GFX_RHI_IMAGE_LAYOUT_DEPTH_STENCIL_ATTACHMENT_OPTIMAL,
  CRUDE_GFX_RHI_IMAGE_LAYOUT_DEPTH_STENCIL_READ_ONLY_OPTIMAL,
  CRUDE_GFX_RHI_IMAGE_LAYOUT_SHADER_READ_ONLY_OPTIMAL,
  CRUDE_GFX_RHI_IMAGE_LAYOUT_TRANSFER_SRC_OPTIMAL,
  CRUDE_GFX_RHI_IMAGE_LAYOUT_TRANSFER_DST_OPTIMAL,
  CRUDE_GFX_RHI_IMAGE_LAYOUT_PREINITIALIZED,
  CRUDE_GFX_RHI_IMAGE_LAYOUT_DEPTH_READ_ONLY_STENCIL_ATTACHMENT_OPTIMAL,
  CRUDE_GFX_RHI_IMAGE_LAYOUT_DEPTH_ATTACHMENT_STENCIL_READ_ONLY_OPTIMAL,
  CRUDE_GFX_RHI_IMAGE_LAYOUT_DEPTH_ATTACHMENT_OPTIMAL,
  CRUDE_GFX_RHI_IMAGE_LAYOUT_DEPTH_READ_ONLY_OPTIMAL,
  CRUDE_GFX_RHI_IMAGE_LAYOUT_STENCIL_ATTACHMENT_OPTIMAL,
  CRUDE_GFX_RHI_IMAGE_LAYOUT_STENCIL_READ_ONLY_OPTIMAL,
  CRUDE_GFX_RHI_IMAGE_LAYOUT_READ_ONLY_OPTIMAL,
  CRUDE_GFX_RHI_IMAGE_LAYOUT_ATTACHMENT_OPTIMAL,
  CRUDE_GFX_RHI_IMAGE_LAYOUT_RENDERING_LOCAL_READ,
  CRUDE_GFX_RHI_IMAGE_LAYOUT_PRESENT_SRC_KHR,
  CRUDE_GFX_RHI_IMAGE_LAYOUT_VIDEO_DECODE_DST_KHR,
  CRUDE_GFX_RHI_IMAGE_LAYOUT_VIDEO_DECODE_SRC_KHR,
  CRUDE_GFX_RHI_IMAGE_LAYOUT_VIDEO_DECODE_DPB_KHR,
  CRUDE_GFX_RHI_IMAGE_LAYOUT_SHARED_PRESENT_KHR,
  CRUDE_GFX_RHI_IMAGE_LAYOUT_FRAGMENT_DENSITY_MAP_OPTIMAL_EXT,
  CRUDE_GFX_RHI_IMAGE_LAYOUT_FRAGMENT_SHADING_RATE_ATTACHMENT_OPTIMAL_KHR,
  CRUDE_GFX_RHI_IMAGE_LAYOUT_VIDEO_ENCODE_DST_KHR,
  CRUDE_GFX_RHI_IMAGE_LAYOUT_VIDEO_ENCODE_SRC_KHR,
  CRUDE_GFX_RHI_IMAGE_LAYOUT_VIDEO_ENCODE_DPB_KHR,
  CRUDE_GFX_RHI_IMAGE_LAYOUT_ATTACHMENT_FEEDBACK_LOOP_OPTIMAL_EXT,
  CRUDE_GFX_RHI_IMAGE_LAYOUT_TENSOR_ALIASING_ARM,
  CRUDE_GFX_RHI_IMAGE_LAYOUT_VIDEO_ENCODE_QUANTIZATION_MAP_KHR,
  CRUDE_GFX_RHI_IMAGE_LAYOUT_ZERO_INITIALIZED_EXT,
  CRUDE_GFX_RHI_IMAGE_LAYOUT_DEPTH_READ_ONLY_STENCIL_ATTACHMENT_OPTIMAL_KHR,
  CRUDE_GFX_RHI_IMAGE_LAYOUT_DEPTH_ATTACHMENT_STENCIL_READ_ONLY_OPTIMAL_KHR,
  CRUDE_GFX_RHI_IMAGE_LAYOUT_SHADING_RATE_OPTIMAL_NV,
  CRUDE_GFX_RHI_IMAGE_LAYOUT_RENDERING_LOCAL_READ_KHR,
  CRUDE_GFX_RHI_IMAGE_LAYOUT_DEPTH_ATTACHMENT_OPTIMAL_KHR,
  CRUDE_GFX_RHI_IMAGE_LAYOUT_DEPTH_READ_ONLY_OPTIMAL_KHR,
  CRUDE_GFX_RHI_IMAGE_LAYOUT_STENCIL_ATTACHMENT_OPTIMAL_KHR,
  CRUDE_GFX_RHI_IMAGE_LAYOUT_STENCIL_READ_ONLY_OPTIMAL_KHR,
  CRUDE_GFX_RHI_IMAGE_LAYOUT_READ_ONLY_OPTIMAL_KHR,
  CRUDE_GFX_RHI_IMAGE_LAYOUT_ATTACHMENT_OPTIMAL_KHR,
  CRUDE_GFX_RHI_IMAGE_LAYOUT_MAX_ENUM,
} crude_gfx_rhi_image_layout;

typedef enum crude_gfx_rhi_cull_mode_flags_bits
{
  CRUDE_GFX_RHI_CULL_MODE_NONE,
  CRUDE_GFX_RHI_CULL_MODE_FRONT_BIT,
  CRUDE_GFX_RHI_CULL_MODE_BACK_BIT,
  CRUDE_GFX_RHI_CULL_MODE_FRONT_AND_BACK,
  CRUDE_GFX_RHI_CULL_MODE_FLAG_BITS_MAX_ENUM,
} crude_gfx_rhi_cull_mode_flags_bits;

typedef enum crude_gfx_rhi_front_face
{
  CRUDE_GFX_RHI_FRONT_FACE_COUNTER_CLOCKWISE,
  CRUDE_GFX_RHI_FRONT_FACE_CLOCKWISE,
  CRUDE_GFX_RHI_FRONT_FACE_MAX_ENUM,
} crude_gfx_rhi_front_face;

typedef enum crude_gfx_rhi_image_view_type
{
  CRUDE_GFX_RHI_IMAGE_VIEW_TYPE_1D,
  CRUDE_GFX_RHI_IMAGE_VIEW_TYPE_2D,
  CRUDE_GFX_RHI_IMAGE_VIEW_TYPE_3D,
  CRUDE_GFX_RHI_IMAGE_VIEW_TYPE_CUBE,
  CRUDE_GFX_RHI_IMAGE_VIEW_TYPE_1D_ARRAY,
  CRUDE_GFX_RHI_IMAGE_VIEW_TYPE_2D_ARRAY,
  CRUDE_GFX_RHI_IMAGE_VIEW_TYPE_CUBE_ARRAY,
  CRUDE_GFX_RHI_IMAGE_VIEW_TYPE_MAX_ENUM,
} crude_gfx_rhi_image_view_type;

typedef enum crude_gfx_rhi_shader_stage_flag_bits
{
  CRUDE_GFX_RHI_SHADER_STAGE_VERTEX_BIT,
  CRUDE_GFX_RHI_SHADER_STAGE_TESSELLATION_CONTROL_BIT,
  CRUDE_GFX_RHI_SHADER_STAGE_TESSELLATION_EVALUATION_BIT,
  CRUDE_GFX_RHI_SHADER_STAGE_GEOMETRY_BIT,
  CRUDE_GFX_RHI_SHADER_STAGE_FRAGMENT_BIT,
  CRUDE_GFX_RHI_SHADER_STAGE_COMPUTE_BIT,
  CRUDE_GFX_RHI_SHADER_STAGE_ALL_GRAPHICS,
  CRUDE_GFX_RHI_SHADER_STAGE_ALL,
  CRUDE_GFX_RHI_SHADER_STAGE_RAYGEN_BIT_KHR,
  CRUDE_GFX_RHI_SHADER_STAGE_ANY_HIT_BIT_KHR,
  CRUDE_GFX_RHI_SHADER_STAGE_CLOSEST_HIT_BIT_KHR,
  CRUDE_GFX_RHI_SHADER_STAGE_MISS_BIT_KHR,
  CRUDE_GFX_RHI_SHADER_STAGE_INTERSECTION_BIT_KHR,
  CRUDE_GFX_RHI_SHADER_STAGE_CALLABLE_BIT_KHR,
  CRUDE_GFX_RHI_SHADER_STAGE_TASK_BIT_EXT,
  CRUDE_GFX_RHI_SHADER_STAGE_MESH_BIT_EXT,
  CRUDE_GFX_RHI_SHADER_STAGE_SUBPASS_SHADING_BIT_HUAWEI,
  CRUDE_GFX_RHI_SHADER_STAGE_CLUSTER_CULLING_BIT_HUAWEI,
  CRUDE_GFX_RHI_SHADER_STAGE_RAYGEN_BIT_NV,
  CRUDE_GFX_RHI_SHADER_STAGE_ANY_HIT_BIT_NV,
  CRUDE_GFX_RHI_SHADER_STAGE_CLOSEST_HIT_BIT_NV,
  CRUDE_GFX_RHI_SHADER_STAGE_MISS_BIT_NV,
  CRUDE_GFX_RHI_SHADER_STAGE_INTERSECTION_BIT_NV,
  CRUDE_GFX_RHI_SHADER_STAGE_CALLABLE_BIT_NV,
  CRUDE_GFX_RHI_SHADER_STAGE_TASK_BIT_NV,
  CRUDE_GFX_RHI_SHADER_STAGE_MESH_BIT_NV,
  CRUDE_GFX_RHI_SHADER_STAGE_FLAG_BITS_MAX_ENUM,
} crude_gfx_rhi_shader_stage_flag_bits;

typedef enum crude_gfx_rhi_descriptor_type
{
  CRUDE_GFX_RHI_DESCRIPTOR_TYPE_SAMPLER,
  CRUDE_GFX_RHI_DESCRIPTOR_TYPE_COMBINED_IMAGE_SAMPLER,
  CRUDE_GFX_RHI_DESCRIPTOR_TYPE_SAMPLED_IMAGE,
  CRUDE_GFX_RHI_DESCRIPTOR_TYPE_STORAGE_IMAGE,
  CRUDE_GFX_RHI_DESCRIPTOR_TYPE_UNIFORM_TEXEL_BUFFER,
  CRUDE_GFX_RHI_DESCRIPTOR_TYPE_STORAGE_TEXEL_BUFFER,
  CRUDE_GFX_RHI_DESCRIPTOR_TYPE_UNIFORM_BUFFER,
  CRUDE_GFX_RHI_DESCRIPTOR_TYPE_STORAGE_BUFFER,
  CRUDE_GFX_RHI_DESCRIPTOR_TYPE_UNIFORM_BUFFER_DYNAMIC,
  CRUDE_GFX_RHI_DESCRIPTOR_TYPE_STORAGE_BUFFER_DYNAMIC,
  CRUDE_GFX_RHI_DESCRIPTOR_TYPE_INPUT_ATTACHMENT,
  CRUDE_GFX_RHI_DESCRIPTOR_TYPE_INLINE_UNIFORM_BLOCK,
  CRUDE_GFX_RHI_DESCRIPTOR_TYPE_ACCELERATION_STRUCTURE_KHR,
  CRUDE_GFX_RHI_DESCRIPTOR_TYPE_ACCELERATION_STRUCTURE_NV,
  CRUDE_GFX_RHI_DESCRIPTOR_TYPE_SAMPLE_WEIGHT_IMAGE_QCOM,
  CRUDE_GFX_RHI_DESCRIPTOR_TYPE_BLOCK_MATCH_IMAGE_QCOM,
  CRUDE_GFX_RHI_DESCRIPTOR_TYPE_TENSOR_ARM,
  CRUDE_GFX_RHI_DESCRIPTOR_TYPE_MUTABLE_EXT,
  CRUDE_GFX_RHI_DESCRIPTOR_TYPE_PARTITIONED_ACCELERATION_STRUCTURE_NV,
  CRUDE_GFX_RHI_DESCRIPTOR_TYPE_INLINE_UNIFORM_BLOCK_EXT,
  CRUDE_GFX_RHI_DESCRIPTOR_TYPE_MUTABLE_VALVE,
  CRUDE_GFX_RHI_DESCRIPTOR_TYPE_MAX_ENUM,
} crude_gfx_rhi_descriptor_type;

typedef enum crude_gfx_rhi_primitive_topology
{
  CRUDE_GFX_RHI_PRIMITIVE_TOPOLOGY_POINT_LIST,
  CRUDE_GFX_RHI_PRIMITIVE_TOPOLOGY_LINE_LIST,
  CRUDE_GFX_RHI_PRIMITIVE_TOPOLOGY_LINE_STRIP,
  CRUDE_GFX_RHI_PRIMITIVE_TOPOLOGY_TRIANGLE_LIST,
  CRUDE_GFX_RHI_PRIMITIVE_TOPOLOGY_TRIANGLE_STRIP,
  CRUDE_GFX_RHI_PRIMITIVE_TOPOLOGY_TRIANGLE_FAN,
  CRUDE_GFX_RHI_PRIMITIVE_TOPOLOGY_LINE_LIST_WITH_ADJACENCY,
  CRUDE_GFX_RHI_PRIMITIVE_TOPOLOGY_LINE_STRIP_WITH_ADJACENCY,
  CRUDE_GFX_RHI_PRIMITIVE_TOPOLOGY_TRIANGLE_LIST_WITH_ADJACENCY,
  CRUDE_GFX_RHI_PRIMITIVE_TOPOLOGY_TRIANGLE_STRIP_WITH_ADJACENCY,
  CRUDE_GFX_RHI_PRIMITIVE_TOPOLOGY_PATCH_LIST,
  CRUDE_GFX_RHI_PRIMITIVE_TOPOLOGY_MAX_ENUM,
} crude_gfx_rhi_primitive_topology;

typedef enum crude_gfx_rhi_image_type
{
  CRUDE_GFX_RHI_IMAGE_TYPE_1D,
  CRUDE_GFX_RHI_IMAGE_TYPE_2D,
  CRUDE_GFX_RHI_IMAGE_TYPE_3D,
  CRUDE_GFX_RHI_IMAGE_TYPE_MAX_ENUM,
} crude_gfx_rhi_image_type;

typedef enum crude_gfx_rhi_color_space
{
  CRUDE_GFX_RHI_COLOR_SPACE_SRGB_NONLINEAR_KHR,
  CRUDE_GFX_RHI_COLOR_SPACE_DISPLAY_P3_NONLINEAR_EXT,
  CRUDE_GFX_RHI_COLOR_SPACE_EXTENDED_SRGB_LINEAR_EXT,
  CRUDE_GFX_RHI_COLOR_SPACE_DISPLAY_P3_LINEAR_EXT,
  CRUDE_GFX_RHI_COLOR_SPACE_DCI_P3_NONLINEAR_EXT,
  CRUDE_GFX_RHI_COLOR_SPACE_BT709_LINEAR_EXT,
  CRUDE_GFX_RHI_COLOR_SPACE_BT709_NONLINEAR_EXT,
  CRUDE_GFX_RHI_COLOR_SPACE_BT2020_LINEAR_EXT,
  CRUDE_GFX_RHI_COLOR_SPACE_HDR10_ST2084_EXT,
  CRUDE_GFX_RHI_COLOR_SPACE_DOLBYVISION_EXT,
  CRUDE_GFX_RHI_COLOR_SPACE_HDR10_HLG_EXT,
  CRUDE_GFX_RHI_COLOR_SPACE_ADOBERGB_LINEAR_EXT,
  CRUDE_GFX_RHI_COLOR_SPACE_ADOBERGB_NONLINEAR_EXT,
  CRUDE_GFX_RHI_COLOR_SPACE_PASS_THROUGH_EXT,
  CRUDE_GFX_RHI_COLOR_SPACE_EXTENDED_SRGB_NONLINEAR_EXT,
  CRUDE_GFX_RHI_COLOR_SPACE_DISPLAY_NATIVE_AMD,
  CRUDE_GFX_COLORSPACE_SRGB_NONLINEAR_KHR,
  CRUDE_GFX_RHI_COLOR_SPACE_DCI_P3_LINEAR_EXT,
  CRUDE_GFX_RHI_COLOR_SPACE_MAX_ENUM_KHR,
} crude_gfx_rhi_color_space;

typedef enum crude_gfx_rhi_ray_tracing_shader_group_type
{
  CRUDE_GFX_RAY_TRACING_SHADER_GROUP_TYPE_GENERAL_KHR,
  CRUDE_GFX_RAY_TRACING_SHADER_GROUP_TYPE_TRIANGLES_HIT_GROUP_KHR,
  CRUDE_GFX_RAY_TRACING_SHADER_GROUP_TYPE_PROCEDURAL_HIT_GROUP_KHR,
  CRUDE_GFX_RAY_TRACING_SHADER_GROUP_TYPE_GENERAL_NV,
  CRUDE_GFX_RAY_TRACING_SHADER_GROUP_TYPE_TRIANGLES_HIT_GROUP_NV,
  CRUDE_GFX_RAY_TRACING_SHADER_GROUP_TYPE_PROCEDURAL_HIT_GROUP_NV,
  CRUDE_GFX_RAY_TRACING_SHADER_GROUP_TYPE_MAX_ENUM_KHR,
} crude_gfx_rhi_ray_tracing_shader_group_type;

typedef enum crude_gfx_rhi_queue_type
{
  CRUDE_GFX_RHI_QUEUE_TYPE_GRAPHICS,
  CRUDE_GFX_RHI_QUEUE_TYPE_COMPUTE,
  CRUDE_GFX_RHI_QUEUE_TYPE_COPY_TRANSFER,
  CRUDE_GFX_RHI_QUEUE_TYPE_COUNT
} crude_gfx_rhi_queue_type;

typedef struct crude_gfx_rhi_surface_format
{
  crude_gfx_rhi_format                                         format;
  crude_gfx_rhi_color_space                                    color_space;
} crude_gfx_rhi_surface_format;

typedef uint64 crude_gfx_rhi_buffer_usage_flags;
typedef uint64 crude_gfx_rhi_access_flags;
typedef uint64 crude_gfx_rhi_pipeline_stage_flags;
typedef uint64 crude_gfx_rhi_pipeline_shader_stage_create_flags;

typedef struct crude_gfx_rhi_buffer
{
} crude_gfx_rhi_buffer;

typedef struct crude_gfx_rhi_sampler
{
} crude_gfx_rhi_sampler;

typedef struct crude_gfx_rhi_image
{
} crude_gfx_rhi_image;

typedef struct crude_gfx_rhi_image_view
{
} crude_gfx_rhi_image_view;

typedef struct crude_gfx_rhi_descriptor_pool
{
} crude_gfx_rhi_descriptor_pool;

typedef struct crude_gfx_rhi_descriptor_set_layout
{
} crude_gfx_rhi_descriptor_set_layout;

typedef struct crude_gfx_rhi_descriptor_set_layout_binding
{
} crude_gfx_rhi_descriptor_set_layout_binding;

typedef struct crude_gfx_rhi_descriptor_set
{
} crude_gfx_rhi_descriptor_set;

typedef struct crude_gfx_rhi_acceleration_structure
{
} crude_gfx_rhi_acceleration_structure;

typedef struct crude_gfx_rhi_pipeline
{
} crude_gfx_rhi_pipeline;

typedef struct crude_gfx_rhi_pipeline_layout
{
} crude_gfx_rhi_pipeline_layout;

typedef struct crude_gfx_rhi_pipeline_bind_point
{
} crude_gfx_rhi_pipeline_bind_point;

typedef struct crude_gfx_rhi_command_pool
{
} crude_gfx_rhi_command_pool;

typedef struct crude_gfx_rhi_query_pool
{
} crude_gfx_rhi_query_pool;

typedef struct crude_gfx_rhi_command_buffer
{
} crude_gfx_rhi_command_buffer;

typedef struct crude_gfx_rhi_shader_module
{
} crude_gfx_rhi_shader_module;

typedef union crude_gfx_rhi_clear_color_value
{
  float32                                                  float32[ 4 ];
  int32                                                    int32[ 4 ];
  uint32                                                   uint32[ 4 ];
} crude_gfx_rhi_clear_color_value;

typedef struct crude_gfx_rhi_clear_depth_stencil_value
{
  float32                                                  depth;
  uint32                                                   stencil;
} crude_gfx_rhi_clear_depth_stencil_value;

typedef union crude_gfx_rhi_clear_value
{
  crude_gfx_rhi_clear_color_value                          color;
  crude_gfx_rhi_clear_depth_stencil_value                  depth_stencil;
} crude_gfx_rhi_clear_value;

typedef struct crude_gfx_rhi_pipeline_shader_stage_create_info
{
  void const                                              *next;
  crude_gfx_rhi_pipeline_shader_stage_create_flags         flags;
  crude_gfx_rhi_shader_stage_flag_bits                     stage;
  crude_gfx_rhi_shader_module                              module;
  char const                                              *name;
} crude_gfx_rhi_pipeline_shader_stage_create_info;

typedef struct crude_gfx_rhi_ray_tracing_shader_group_create_info
{
  void const                                              *next;
  crude_gfx_rhi_ray_tracing_shader_group_type              type;
  uint32                                                   general_shader;
  uint32                                                   closest_hit_shader;
  uint32                                                   any_hit_shader;
  uint32                                                   intersection_shader;
} crude_gfx_rhi_ray_tracing_shader_group_create_info;

CRUDE_API bool
crude_gfx_rhi_format_has_depth_or_stencil
( 
  _In_ crude_gfx_rhi_format                                    value
);

CRUDE_API bool
crude_gfx_rhi_format_has_depth
( 
  _In_ crude_gfx_rhi_format                                    value
);

CRUDE_API crude_gfx_rhi_blend_factor
crude_gfx_rhi_string_to_blend_factor
(
  _In_ char const                                         *factor
);

CRUDE_API crude_gfx_rhi_blend_op
crude_gfx_rhi_string_to_blend_op
(
  _In_ char const                                         *op
);

CRUDE_API crude_gfx_rhi_access_flags
crude_gfx_rhi_resource_state_to_access_flags
(
  _In_ crude_gfx_rhi_resource_state                        state
);

CRUDE_API crude_gfx_rhi_image_layout
crude_gfx_rhi_resource_state_to_image_layout
(
  _In_ crude_gfx_rhi_resource_state                        state
);

CRUDE_API crude_gfx_rhi_pipeline_stage_flags
crude_gfx_rhi_determine_pipeline_stage_flags
(
  _In_ crude_gfx_rhi_access_flags                          access_flags,
  _In_ crude_gfx_rhi_queue_type                            queue_type
);

#else
CRUDE_GFX_RHI_TO_IMPLEMENTIT
#endif